from independent import *
import shutil
z=freeze('sealed-after');assert json.loads((ROOT/'source-before.json').read_text())==z
paths=['csv_logic_reuse.py','csv_dag.py','csv_dag_instances.py','csv_material_reuse.py','internal_api.py','api.py','web/app.js','web/index.html','web/csv-dag.js','web/csv-logic.js']
for q in paths:
 p='src/sim2act/'+q;t=ROOT/'source'/p;t.parent.mkdir(parents=True,exist_ok=True);t.write_bytes((REPO/p).read_bytes());assert hashlib.sha256(t.read_bytes()).hexdigest()==z['files'][p]['sha256']
contract=REPO/'docs/F2/CsvDataFreeLogicSafety20261010.md';b=contract.read_bytes();assert hashlib.sha256(b).hexdigest()=='014dc78e6e29772ce4d37400c0150ed52f7c37adcf8aafc843b3bec768acacd8';(ROOT/'contract-014.md').write_bytes(b);shutil.copyfile('/tmp/sim2act-csv-data-free-logic-20261010/source-freeze-fixed.json',ROOT/'author-source-freeze-fixed.json')
src=[p for p in z['files'] if p.startswith('src/')];bridge=[p for p in src if subprocess.check_output(['git','show','4e66136866d5a46347785af45f517dd75de1aeac:'+p],cwd=REPO)!=(REPO/p).read_bytes()];assert bridge==['src/sim2act/csv_logic_reuse.py'];(ROOT/'SOURCE_BRIDGE.json').write_text(json.dumps({'source_sha':SHA,'previous_BLOCK_source':'4e66136866d5a46347785af45f517dd75de1aeac','products':72,'unchanged71':True,'changed':bridge,'all_final_matrix_actual4a4b':True},indent=2))
backend=json.loads((ROOT/'BACKEND_RESULTS.json').read_text());extra=json.loads((ROOT/'EXTRA_RESULTS.json').read_text());ui=json.loads((ROOT/'UI_RESULTS.json').read_text());assert len(backend['records'])==54 and len(extra['records'])==4 and backend['check_count']==234 and extra['check_count']==18;assert all(v['status']=='PASS' for v in ui) and sum(v['checks'] for v in ui)==110
cleanups=list(ROOT.glob('*/own-schema-cleanup.json'));assert len(cleanups)==3
for p in cleanups:assert json.loads(p.read_text())['own_schema_absent']
observer={'source_sha':SHA,'scope':'Product query old-id checks, not a claim that the entire independent harness never reads old synthetic rows','observed_gate':'No SELECT binding original resource ID against resources; no SELECT binding original Run ID against operations or projected runs.result, across registry/material/actual worker/new Release/Instance/cold reads','oracle_exception':'All-table snapshot queries intentionally SELECT own synthetic operations/runs including old rows to prove zero product writes. Unfiltered full-table statements in source-read-observer.json are independent oracle queries.','static_audit_gate':'audit() directly projects old Run id/principal/project/runtime/status/version/fence/fingerprint and App id/project/runtime only; sealed release/approval JSON is hashed/joined, not old CSV execution input'};(ROOT/'OBSERVER_SCOPE.json').write_text(json.dumps(observer,indent=2))
print('sealed exact source378/product72, scenarios58, actual runtimechecks250, HTTP4/110',flush=True)
