import pathlib,json,hashlib
R=pathlib.Path('/tmp/sim2act-native-remaining11-independent-180a-20261010');data=json.loads((R/'results.json').read_text());assert len(data['Report_cases'])==17 and all(r['status']=='PASS' for r in data['Report_cases']);sha='180a4710405b9c06d1e7cc7213b3ffd073d05567'
review={'verdict':'LIMITED_PASS','source_sha':sha,'base_sha':'5385ac9293737cca8ed5dfeec990b760b240bf63','scope':'remaining11 semantic evidence proof-gate delta only','actual_Report_CLI_cases':17,'accepted_positive':1,'refused_negative':16,'old_source_sensitivity_checks':2,'Recorder_hook_positive_checks':3,'total_named_cases_or_checks':22,'original_d49_four_and5385_six_attacks_refused':True,'whole_alternative11_trace_refused':True,'freeze363_before_after_match':True,'unchanged_frozen_vs5385':361,'products_same473':69,'other_diagnostic_AST_same5385':True,'head_commit_explicit_remaining11_marker':True,'old_BLOCK_preserved':{'d49':'/tmp/sim2act-native-remaining11-independent-20261010','5385':'/tmp/sim2act-native-remaining11-independent-5385-20261010'},'limits':{'trace_phase_materials_synthetic':True,'target11_tests_executed':False,'native_Windows_PowerShell':False,'CI_PG':False,'real_models':0,'source_tests_refs_writes':False},'remaining':'Native11/full/Edge/Windows acceptance awaits actual run; historical Report idle6 and PG resources-history Future10 OPEN; PROJECT PENDING/BLOCKED_PARTIAL; LIVE0'}
(R/'FINAL_REVIEW.json').write_text(json.dumps(review,indent=2));(R/'FINAL_REVIEW.md').write_text('''# Final incremental remaining11 proof review: LIMITED_PASS

Exact180a4710405b9c06d1e7cc7213b3ffd073d05567; base5385ac9293737cca8ed5dfeec990b760b240bf63. Scope is the semantic diagnostic-evidence closure delta, not execution/acceptance of the Windows target11.

17 independently authored actual Report CLI cases all behave correctly: one valid lifecycle trace accepts;16 negative variants reject. Positive material calls the real Recorder's session-start, collection-modify, collection-finish, per-node start/report/finish and session-finish hooks, retaining genuine PID/UTC/elapsed metadata. A reversed full12-item list is reordered to the fixed11 with exactly one extra item deselected;33passed reports and11finish records are emitted by actual hooks. Reports themselves are synthetic bounded materials, not test execution claims.

The originald49 four defects (missingselection,missingfull,wronghash,wrongcount) and5385 six semantic defects (foreignstart,foreignfinish,wrongrequestevent,extranonrequestedsession,extranodephase,outoforder) now all return nonzero/required_complete=false. Replacing the entire request/selection/collection/start/report/finish set with another11 while recomputing all metadata hashes also refuses. Skip, exit2 interruption, partial JSON tail, foreignPID and wrong selection scope refuse; scope output remains DIAGNOSTIC_ONLY_REMAINING11. Full valid proof alone returns0 and complete=true.

Two exact old-source sensitivity controls on these same corrected negative materials reproduce d49 missingselection and5385 foreignstart falsePASS. The original55-file d49 and64-file5385 BLOCK roots remain separately sealed; this result does not rewrite their status. Three bounded Recorder wiring checks and the two old-source sensitivity checks accompany17CLI cases (22 named cases/checks total). All private traces, Report/summary/step-summary outputs and old-source logs are preserved.

363paths match exact Git,manifest,worktree before/after. Only diagnostic summarize and its tests differ from5385;361other frozen files are identical and all69src remain same47388f573746daa27f8d5790ca358eef91378ad5. Other diagnostic functions/classes have identical ASTs; earlier default/fullscope/PS/workflow/Node-lock/redaction checks are bridged without rerunning their matrices. Immutable180a commit message contains the explicit[native-remaining11] marker, consistent with the already reviewed workflow's fixed diagnostic opt-in path. No new fullcollection count is invented from prior freezes.

No CI/native/PowerShell/PG/real model was operated; no source/tests/refs modified. The current native11 run has not been executed by this review, and no whole native/Edge/Windows11 acceptance is inferred. Parent's additional PG measurements are outside this independent scope. Historical Report GET idle6 and PG resources-history Future10 remainOPEN; PROJECT PENDING/BLOCKED_PARTIAL, LIVE0. Ordinary authorized integration may proceed based on this limited proof-gate result; actual native results remain separately required. Copy only SHA256-listed files; do not overwrite prior sealed roots.
''')
paths=[p for p in sorted(R.rglob('*')) if p.is_file() and p.name!='COPY_WHITELIST.json' and '__pycache__' not in p.parts];(R/'COPY_WHITELIST.json').write_text(json.dumps({'artifact_root':str(R),'source_sha':sha,'verdict':'LIMITED_PASS','count':len(paths),'files':[{'path':str(p.relative_to(R)),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size} for p in paths]},indent=2));print(json.dumps({'verdict':'LIMITED_PASS','source_sha':sha,'namedcases_checks':22,'whitelist_count':len(paths)}))
