import pathlib,json,hashlib,re,base64,datetime,collections,struct,subprocess,xml.etree.ElementTree as ET
R=pathlib.Path('/tmp/sim2act-native-remaining11-terminal-independent-20261010');P=pathlib.Path('/tmp/sim2act-native-remaining11-20261010');REPO=pathlib.Path('/workspace/Sim2Act');SHA='180a4710405b9c06d1e7cc7213b3ffd073d05567';B=P/'browser-emitted';raw=(P/'ci-final-full.log').read_bytes();transport=json.loads((P/'ci-final-full.transport.json').read_text());assert isinstance(transport,str) and transport.encode('utf-8')==raw and len(raw)==4797111 and hashlib.sha256(raw).hexdigest()=='5d4dc70dbeebccd4e704f3fe65c366f99221691b9878fad6fa6449a0cf37ecd5';lines=raw.decode('utf-8').splitlines();clean=[re.sub(r'^\d{4}-\d\d-\d\dT\S+ ', '',s) for s in lines]
records=[];chunks={};browser_meta={};browser_chunks={};summary=None
for t in clean:
 if t.startswith('SIM2ACT_CI_DIAGNOSTIC '):records.append(json.loads(t[len('SIM2ACT_CI_DIAGNOSTIC '):]))
 elif t.startswith('SIM2ACT_CI_FULL_COLLECTION '):d=json.loads(t[len('SIM2ACT_CI_FULL_COLLECTION '):]);assert d['offset'] not in chunks;chunks[d['offset']]=d['nodes']
 elif t.startswith('Engineering diagnostics: '):assert summary is None;summary=json.loads(t[len('Engineering diagnostics: '):])
 elif t.startswith('SIM2ACT_BROWSER_FILE '):d=json.loads(t[len('SIM2ACT_BROWSER_FILE '):]);assert d['name'] not in browser_meta;browser_meta[d['name']]=d
 elif t.startswith('SIM2ACT_BROWSER_CHUNK '):_,name,index,data=t.split(' ',3);i=int(index);table=browser_chunks.setdefault(name,{});assert i not in table;table[i]=data
assert records==json.loads((P/'ci-final-visible-events.json').read_text());assert summary==json.loads((P/'ci-final-summary.json').read_text());expected_nodes=json.loads((REPO/'scripts/native-remaining11.json').read_text());assert len(expected_nodes)==11 and len(set(expected_nodes))==11
assert sorted(chunks)==list(range(0,2250,20));full=[n for offset in sorted(chunks) for n in chunks[offset]];assert len(full)==len(set(full))==2250 and full==json.loads((P/'ci-final-full-collection.json').read_text());digest=hashlib.sha256(json.dumps(full).encode()).hexdigest();assert digest=='92ac8b50767b888a5b177467d5c4f85abd80d6f29118194c3a3d01d598c58cfc'
visible_expected=[('session_start',None,None),('selection',None,None),('collection_summary',None,None)]
for node in expected_nodes:visible_expected.extend([('node_start',node,None),('node_report',node,'setup'),('node_report',node,'call'),('node_report',node,'teardown'),('node_finish',node,None)])
visible_expected.append(('session_finish',None,None));actual=[(r['event'],r.get('nodeid'),r.get('phase')) for r in records];assert actual==visible_expected and len(records)==59;pid=records[0]['pid'];assert isinstance(pid,int) and not isinstance(pid,bool) and pid>0 and all(type(r['pid']) is int and r['pid']==pid for r in records);assert all(records[i]['elapsed_seconds']<=records[i+1]['elapsed_seconds'] for i in range(len(records)-1));assert records[0]['requested_scope']=='DIAGNOSTIC_ONLY_REMAINING11' and records[0]['required_nodes']==expected_nodes
selection=records[1];assert selection['scope']=='DIAGNOSTIC_ONLY_REMAINING11' and selection['required_nodes']==expected_nodes and selection['full_count']==2250 and selection['full_nodes_sha256']==digest and selection['deselected_count']==2239;assert records[2]['count']==11 and records[2]['nodes_sha256']==hashlib.sha256(json.dumps(expected_nodes).encode()).hexdigest();phase_records=[r for r in records if r['event']=='node_report'];assert len(phase_records)==33 and all(r['outcome']=='passed' for r in phase_records);assert records[-1]['exitstatus']==0
assert summary['collected']==summary['started']==summary['finished']==11 and summary['active_nodes']==[] and summary['not_started_count']==0 and summary['exitstatuses']==[0] and summary['incomplete_tail'] is False and summary['suite_complete'] and summary['required_targets_complete'] and summary['selection_verified'] and summary['failure_reports']==0 and summary['deselected_count']==2239
assert summary['junit'][0]['tests']=='11' and summary['junit'][0]['failures']==summary['junit'][0]['errors']==summary['junit'][0]['skipped']=='0' and summary['junit'][0]['time']=='113.781';assert set(summary['required_outcomes'])==set(expected_nodes) and all(phases=={'setup':['passed'],'call':['passed'],'teardown':['passed']} for phases in summary['required_outcomes'].values());result=json.loads((P/'ci-final-result.json').read_text());assert result['source_sha']==SHA and result['scope']=='DIAGNOSTIC_ONLY_REMAINING11' and result['full_engineering_acceptance']=='NOT_ACCEPTED' and result['passed']==11 and result['node_reports']==33
# Independently reassemble original artifact chunks; no rerun or image-edit tool.
browser_chunks={}
for name,index,data in re.findall(r'SIM2ACT_BROWSER_CHUNK ([^\s]+) (\d+) ([A-Za-z0-9+/=]+)',raw.decode('utf-8')):
 table=browser_chunks.setdefault(name,{});assert int(index) not in table;table[int(index)]=data
assert len(browser_meta)==len(browser_chunks)==9 and set(browser_meta)==set(browser_chunks)=={p.name for p in B.iterdir() if p.is_file()};assert list(browser_meta.values())==json.loads((P/'ci-final-browser-files.json').read_text());browser_proofs=[]
for name,meta in browser_meta.items():
 table=browser_chunks[name];assert sorted(table)==list(range(meta['chunks']));data=base64.b64decode(''.join(table[i] for i in sorted(table)),validate=True);assert data==(B/name).read_bytes() and len(data)==meta['bytes'] and hashlib.sha256(data).hexdigest()==meta['sha256'];proof={'name':name,'bytes':len(data),'sha256':meta['sha256'],'chunks':meta['chunks'],'exact_reassembly':True}
 if name.endswith('.png'):assert data[:8]==b'\x89PNG\r\n\x1a\n' and data[12:16]==b'IHDR';proof['width'],proof['height']=struct.unpack('>II',data[16:24])
 else:
  d=json.loads(data);assert d['status']=='PASS' and all(c['status']=='PASS' for c in d['checks']) and d['win11']=='NOT_RUN';proof['recorded_checks']=len(d['checks']);proof['win11']=d['win11'];proof['visual_review']=d.get('visualReview','not independently reviewed')
  if name=='browser-results.json':assert d['commit']==SHA and d['inventory']['runner']=='windows-2025' and d['inventory']['signature']=='Valid' and d['inventory']['sandbox_requested'] and d['chromiumSandbox'] and d['inventory']['job_timeout_minutes']==15 and d['inventory']['browser_step_timeout_minutes']==4 and d['mobileDevice']=='NOT_RUN - viewport only' and d['modelRequests']==0;proof['mobile_device_acceptance']=d['mobileDevice'];proof['platform']='Windows Server2025 installed Edge'
  if name=='agent-results.json':assert d['platform']=='win32' and d['modelRequests']==0 and d['visualReview']=='NOT_REVIEWED'
  if name=='protocol-results.json':assert d['networkProviderRequests']==d['browserReviewRequests']==0 and d['mockProviderRequests']==4 and d['ownerSemanticAcceptance']=='PENDING' and d['formalPublication'] is False and d['visualReview']=='NOT_REVIEWED';proof.update(networkProviderRequests=0,mockProviderRequests=4,ownerSemanticAcceptance='PENDING',formalPublication=False)
 browser_proofs.append(proof)
run=json.loads((P/'ci-final-run.json').read_text());jobs=json.loads((P/'ci-final-jobs.json').read_text())['jobs'];job=next(j for j in jobs if j['id']==114153034590);times=json.loads((P/'ci-final-job-timings.json').read_text());assert run['id']==38031437108 and run['head_sha']==SHA and run['attempt']==1 and run['status']=='completed' and run['conclusion']=='success';assert job['run_id']==run['id'] and job['status']=='completed' and job['conclusion']=='success'
for key in ['id','run_id','status','conclusion']:assert times[key]==job[key]
assert times['head_sha']==run['head_sha'] and 'windows-2025' in times['labels']
for step in times['steps']:
 jstep=next(s for s in job['steps'] if s['number']==step['number']);assert all(step[k]==v for k,v in jstep.items())
def seconds(a,b):return int((datetime.datetime.fromisoformat(b.replace('Z','+00:00'))-datetime.datetime.fromisoformat(a.replace('Z','+00:00'))).total_seconds())
jobsecs=seconds(times['started_at'],times['completed_at']);engineering=next(s for s in times['steps'] if s['number']==6);edge=next(s for s in times['steps'] if s['number']==7);engsecs=seconds(engineering['started_at'],engineering['completed_at']);edgesecs=seconds(edge['started_at'],edge['completed_at']);assert jobsecs==359 and engsecs==129 and edgesecs==141 and jobsecs<900 and edgesecs<240 and all(s['conclusion']=='success' for s in job['steps'])
# Native phase data and metadata are parsed evidence, not reviewer-triggered execution.
f=json.loads((P/'source-freeze.json').read_text());assert f['source_sha']==SHA and len(f['files'])==363
for path,v in f['files'].items():assert hashlib.sha256((REPO/path).read_bytes()).hexdigest()==v and hashlib.sha256(subprocess.check_output(['git','show',SHA+':'+path],cwd=REPO)).hexdigest()==v
src={p:v for p,v in f['files'].items() if p.startswith('src/')};assert len(src)==69
for path,v in src.items():assert hashlib.sha256(subprocess.check_output(['git','show','47388f573746daa27f8d5790ca358eef91378ad5:'+path],cwd=REPO)).hexdigest()==v
# Read parent's finitePG evidence only; preserve oldOPEN rather than infer root cause.
PG=pathlib.Path('/tmp/sim2act-historical-timeouts-20261010');pgresult=json.loads((PG/'test-result.json').read_text());assert pgresult['source_sha']==SHA and pgresult['exit']==0 and pgresult['timeout_changes'] is False and pgresult['observer_unchanged'];xml=list(ET.parse(PG/'pg.xml').getroot().iter('testsuite'));assert sum(int(s.attrib['tests']) for s in xml)==2 and all(s.attrib['failures']==s.attrib['errors']==s.attrib['skipped']=='0' for s in xml);profiles=json.loads((PG/'profile-summary.json').read_text());allprofiles=[r for row in profiles for r in row['records']];reportprofiles=[r for r in allprofiles if r['operation']=='report_presentations.history' and r['sql_count']==4010];resourcesprofiles=[r for r in allprofiles if r['operation']=='delivery_graph_apps.history'];assert len(reportprofiles)==2 and len(resourcesprofiles)==1 and resourcesprofiles[0]['sql_count']==1958;cleanup=json.loads((PG/'pg-cleanup.json').read_text());assert cleanup['container_absent'] and cleanup['owned_anonymous_volumes_removed'];assert json.loads((PG/'pg-after.json').read_text())['counts']=='0|0|0'
summary_out={'verdict':'TERMINAL_EVIDENCE_LIMITED_PASS','source_sha':SHA,'run':38031437108,'job':114153034590,'attempt':1,'transport_bytes':len(raw),'transport_sha256':hashlib.sha256(raw).hexdigest(),'full_collection':2250,'full_collection_chunks':len(chunks),'full_collection_sha256':digest,'selected11_actual_pass':True,'deselected2239':True,'actual_phase_reports':33,'visible_event_sequence':59,'same_positive_pid':True,'strict_native_Report_verified':True,'JUnit_seconds':113.781,'job_seconds':jobsecs,'engineering_step_seconds':engsecs,'Edge_step_seconds':edgesecs,'browser_files':browser_proofs,'product69_same473_and_source363_match':True,'parent_PG_finite2_pass_readonly_verified':True,'PG_profiles':{'Report4010_SQL_wall_seconds':[r['wall_seconds'] for r in reportprofiles],'resources1958_SQL_wall_seconds':resourcesprofiles[0]['wall_seconds']},'limits':['full2250 collection is coverage inventory; only11 engineering cases executed in this run','Windows Server installed Edge limited synthetic page checks only; Win11 NOT_RUN','mobile viewport is not actual device','agent/protocol visual review NOT_REVIEWED; owner semantic PENDING; formalPublicationfalse','parent2PG passes do not explain or close either original timeoutOPEN'],'reviewer_test_CI_PG_operations':0,'repo_ref_writes':0,'public_evidence_audit':'pending root final manifest'}
(R/'TERMINAL_AUDIT.json').write_text(json.dumps(summary_out,indent=2));(R/'independent-visible-sequence.json').write_text(json.dumps(records,indent=2));(R/'independent-browser-reassembly.json').write_text(json.dumps(browser_proofs,indent=2));print(json.dumps({k:v for k,v in summary_out.items() if k!='browser_files'},indent=2))
