"""Independent final regression assertions, disposable synthetic SQLite, no provider calls.
Uses repository test helpers for fixture setup/wire candidates; expected citations are
from frozen hand gold, never generated by runtime checker.
"""
import copy,importlib.util,json,tempfile
from pathlib import Path
from fastapi.testclient import TestClient
from sqlalchemy import select,update
from sim2act.api import create_app
from sim2act.config import Settings
from sim2act.db import Store,fingerprint,operations
from sim2act import app_jobs as jobs
from sim2act.agent_apps import verified_source,check_evidence,extract_agent_candidate
from sim2act.worker import Worker
from sim2act.errors import DomainError
spec=importlib.util.spec_from_file_location('review_fixture',Path(__file__).resolve().parents[3]/'tests/test_bounded_agent_apps.py');mod=importlib.util.module_from_spec(spec);spec.loader.exec_module(mod)
with tempfile.TemporaryDirectory(prefix='independent-agent-review-') as root:
 url='sqlite:///'+root+'/fixture.db';store=Store(url,test_only=True);store.initialize();a=store.user('synthetic A','synthetic-test-A');b=store.user('synthetic B','synthetic-test-B');s=Settings(url,Path(root),mode='mock');client=TestClient(create_app(store,s));client.headers['Authorization']='Bearer synthetic-test-A';pid=client.post('/api/projects',json={'name':'synthetic'}).json()['id'];csv=client.post(f'/api/projects/{pid}/resources',json={'name':'a.csv','format':'csv','content':'x\n1\n'}).json()['id'];env=(store,s,client,a,b,pid,csv)
 runtime,ids,texts,aid,cand,rel,inst,value=mod.setup(env);accepted,result=mod.run(env,inst,rel,ids[0],value)
 with store.tx() as c:
  op=c.execute(select(operations).where(operations.c.run_id==accepted['run_id'])).mappings().one();receipt=copy.deepcopy(op['receipt']);receipt['protocol']['messages']=[];receipt['protocol']['fingerprint']=fingerprint([]);receipt['protocol']['requests']=0;receipt['protocol']['tools']=0;c.execute(update(operations).where(operations.c.id==op['id']).values(receipt=receipt))
 try:
  with store.tx() as c:proof=verified_source(store,c,a,accepted['run_id'],mod.limits(env))
  made=extract_agent_candidate(store,a,accepted['run_id'],fingerprint(proof),mod.candidate(ids[1],texts[1]),runtime,'empty-trace','tamper',mod.limits(env));print('empty protocol trace and zero counters: verified_source accepted and extraction',made['id']);raise AssertionError('Empty protocol accepted')
 except DomainError as e:print('empty protocol trace rejected',type(e).__name__,str(e))
 # Fresh intent: skip compute/Replay entirely, then submit fabricated protocol proof.
 accepted2=jobs.enqueue(store,a,inst['id'],inst['revision'],rel['fingerprint'],{'term':value['term']},'skip-compute',mod.limits(env));worker=Worker(store,s,mod.replay(ids[0],value));claimed=store.claim(worker.id,s.lease_seconds);plan=jobs.prepare_dispatch(worker,claimed);check=check_evidence(plan['source'],plan['args'],value);plan['protocol']={'mode':'OFFLINE_REPLAY','provider_requests':0,'requests':0,'tools':0,'messages':[],'fingerprint':fingerprint([]),'check':check}
 try:
  jobs.commit_result(worker,claimed,plan,value);print('skip Replay/read callback fabricated zero-round protocol: commit accepted',store.inspect(a,accepted2['run_id'])['status']);raise AssertionError('Zero-round protocol committed')
 except DomainError as e:print('skip Replay/read callback rejected',type(e).__name__,str(e))
 client.close();store.engine.dispose()
print('independent review external_requests=0; synthetic local SQLite only')
