"""Independent final regression assertions, disposable synthetic SQLite, no provider calls.
Uses repository test helpers for fixture setup/wire candidates; expected citations are
from frozen hand gold, never generated by runtime checker.
"""
import copy,importlib.util,json,tempfile
from pathlib import Path
from fastapi.testclient import TestClient
from sqlalchemy import select,update
from sim2act.api import create_app
from sim2act.config import Settings
from sim2act.db import Store,fingerprint,operations
from sim2act import app_jobs as jobs
from sim2act.agent_apps import verified_source,check_evidence,extract_agent_candidate
from sim2act.worker import Worker
from sim2act.errors import DomainError
spec=importlib.util.spec_from_file_location('review_fixture',Path(__file__).resolve().parents[3]/'tests/test_bounded_agent_apps.py');mod=importlib.util.module_from_spec(spec);spec.loader.exec_module(mod)
with tempfile.TemporaryDirectory(prefix='independent-agent-review-') as root:
 url='sqlite:///'+root+'/fixture.db';store=Store(url,test_only=True);store.initialize();a=store.user('synthetic A','synthetic-test-A');b=store.user('synthetic B','synthetic-test-B');s=Settings(url,Path(root),mode='mock');client=TestClient(create_app(store,s));client.headers['Authorization']='Bearer synthetic-test-A';pid=client.post('/api/projects',json={'name':'synthetic'}).json()['id'];csv=client.post(f'/api/projects/{pid}/resources',json={'name':'a.csv','format':'csv','content':'x\n1\n'}).json()['id'];env=(store,s,client,a,b,pid,csv)
 runtime,ids,texts,aid,cand,rel,inst,value=mod.setup(env);accepted,result=mod.run(env,inst,rel,ids[0],value)
 with store.tx() as c:
  original_op=c.execute(select(operations).where(operations.c.run_id==accepted['run_id'])).mappings().one();original_receipt=copy.deepcopy(original_op['receipt'])
 print('receipt keys',list(original_receipt))
 for field,bad in [('status','FAILED'),('operation_id','op_'+'0'*32),('instance_id','instance_'+'0'*32),('release_id','irelease_'+'0'*32),('output_fingerprint','0'*64),('artifact_refs',['res_'+'0'*32])]:
  receipt=copy.deepcopy(original_receipt);receipt[field]=bad
  with store.tx() as c:c.execute(update(operations).where(operations.c.id==original_op['id']).values(receipt=receipt))
  try:
   with store.tx() as c:verified_source(store,c,a,accepted['run_id'],mod.limits(env))
   print('corrupt receipt',field,'ACCEPTED by verified_source and cold read',store.inspect(a,accepted['run_id'])['status']);raise AssertionError('Corrupt receipt accepted: '+field)
  except DomainError as e:print('corrupt receipt',field,'REJECTED',type(e).__name__,str(e))
 with store.tx() as c:c.execute(update(operations).where(operations.c.id==original_op['id']).values(receipt=original_receipt))
 # Independent accepted extraction request anchor must retain source identity.
 with store.tx() as c:proof1=verified_source(store,c,a,accepted['run_id'],mod.limits(env))
 target=mod.candidate(ids[1],texts[1]);made=extract_agent_candidate(store,a,accepted['run_id'],fingerprint(proof1),target,runtime,'anchored extraction','anchor',mod.limits(env))
 from sim2act.db import task_extractions,app_drafts
 from sim2act.apps import inspect_draft
 with store.tx() as c:c.execute(update(task_extractions).where(task_extractions.c.app_id==made['id']).values(request_fingerprint='0'*64))
 try:inspect_draft(store,a,made['id'],mod.limits(env));print('extraction independent request_fingerprint zero: ACCEPTED');raise AssertionError('Corrupt accepted request anchor accepted')
 except DomainError as e:print('extraction requestfp zero REJECTED',type(e).__name__,str(e))
 # Another actual valid source AppRun, then coherently substitute marker/provenance.
 accepted3,_=mod.run(env,inst,rel,ids[0],value,key='other-real-source')
 with store.tx() as c:
  proof3=verified_source(store,c,a,accepted3['run_id'],mod.limits(env));draft=c.execute(select(app_drafts).where(app_drafts.c.id==made['id'])).mappings().one();marker=c.execute(select(task_extractions).where(task_extractions.c.app_id==made['id'])).mappings().one();changed=copy.deepcopy(draft['candidate']);changed['agent_provenance']=proof3;changed['manifest']['source_run_ref']=accepted3['run_id'];snap=copy.deepcopy(marker['snapshot']);snap['proof']=proof3;snap['candidate_fingerprint']=fingerprint(changed);c.execute(update(app_drafts).where(app_drafts.c.id==made['id']).values(candidate=changed,fingerprint=fingerprint(changed)));c.execute(update(task_extractions).where(task_extractions.c.app_id==made['id']).values(task_id=accepted3['run_id'],snapshot=snap))
 try:inspect_draft(store,a,made['id'],mod.limits(env));print('coherent switch extraction to other source while accepted requestfp remains zero: ACCEPTED');raise AssertionError('Coherent source substitution accepted')
 except DomainError as e:print('coherent extraction source rewrite REJECTED',type(e).__name__,str(e))
 # Fresh intent: skip compute/Replay entirely, then submit fabricated protocol proof.
 accepted2=jobs.enqueue(store,a,inst['id'],inst['revision'],rel['fingerprint'],{'term':value['term']},'skip-compute',mod.limits(env));worker=Worker(store,s,mod.replay(ids[0],value));claimed=store.claim(worker.id,s.lease_seconds);plan=jobs.prepare_dispatch(worker,claimed);check=check_evidence(plan['source'],plan['args'],value);plan['protocol']={'mode':'OFFLINE_REPLAY','provider_requests':0,'requests':0,'tools':0,'messages':[],'fingerprint':fingerprint([]),'check':check}
 try:
  jobs.commit_result(worker,claimed,plan,value);print('skip Replay/read callback fabricated zero-round protocol: commit accepted',store.inspect(a,accepted2['run_id'])['status']);raise AssertionError('Zero-round protocol committed')
 except DomainError as e:print('skip Replay/read callback rejected',type(e).__name__,str(e))
 client.close();store.engine.dispose()
print('independent review external_requests=0; synthetic local SQLite only')
