'use strict';
// Deterministic slow synthesized API/scheduler; not HTTP, PG, or native evidence.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const root=process.argv[2],source=process.argv[3],web=path.join(__dirname,'../src/sim2act/web'),checks=[];let dom,w,$,tick,requests,gate;
const pid='proj_'+'1'.repeat(32),other='proj_'+'2'.repeat(32),rid='run_'+'3'.repeat(32);
const check=(v,label)=>{assert(v,label);checks.push(label);};
const settle=()=>new Promise(r=>setImmediate(r));
async function setup(){dom?.window.close();dom=new JSDOM(fs.readFileSync(path.join(web,'index.html'),'utf8'),{url:'http://synthetic.invalid',runScripts:'dangerously'});w=dom.window;$=id=>w.document.getElementById(id);requests=[];gate=null;
 w.setInterval=(fn,delay)=>{assert.equal(delay,2500);tick=fn;return 1;};w.crypto.randomUUID=()=>crypto.randomUUID();
 w.fetch=async(url,opts={})=>{const method=opts.method||'GET',record={path:url,method,body:opts.body&&JSON.parse(opts.body)};requests.push(record);let body;
 if(gate&&!gate.used&&gate.path===url){gate.used=true;body=await new Promise((resolve,reject)=>{gate.resolve=resolve;gate.reject=reject;});}
 if(method==='POST')throw Error('synthesized lost acceptance, not actual HTTP');
 if(body===undefined){if(url==='/health')body={mode:'MOCK',api:'up',worker:'up'};else if(url==='/api/apps'||url.endsWith('/goal-cards'))body={items:[]};else if(url.startsWith('/api/runs/'))body={id:rid,status:'SUCCEEDED',namespace:'INTERNAL_APPRUN',version:1,events:[],result:null};else body=[];}
 return {ok:true,status:200,json:async()=>body};};
 const script=w.document.createElement('script');script.textContent=fs.readFileSync(source,'utf8');w.document.body.append(script);$('project-select').append(new w.Option('A',pid),new w.Option('B',other));$('project-select').value=pid;w.eval('token="synthetic-A";');
}
function arm(phase){gate={path:phase==='health'?'/health':phase==='refresh'?`/api/projects/${pid}/resources`:`/api/runs/${rid}`,used:false};if(phase==='showRun')w.eval(`activeRun=${JSON.stringify(rid)}`);}
function value(phase){return phase==='health'?{mode:'MOCK',api:'up',worker:'up'}:phase==='refresh'?[]:{id:rid,status:'SUCCEEDED',namespace:'INTERNAL_APPRUN',version:1,events:[],result:null};}
async function pending(phase){arm(phase);const p=tick();for(let i=0;i<50&&!gate.used;i++)await settle();assert(gate.used,'phase reached');return {promise:p};}
(async()=>{try{
 for(const phase of ['health','refresh','showRun'])for(const failure of [false,true]){
  await setup();const {promise}=await pending(phase);const h=requests.filter(r=>r.path==='/health').length;await tick();check(requests.filter(r=>r.path==='/health').length===h,phase+' pending blocks only next background tick');
  if(failure)gate.reject(Error('controlled slow synthesized API failure'));else gate.resolve(value(phase));await promise;await tick();check(requests.filter(r=>r.path==='/health').length===h+1,phase+' '+(failure?'error':'completion')+' finally releases latch');
 }
 await setup();const {promise}=await pending('health');const before=requests.length;await w.refresh();check(requests.length>before&&requests.some(r=>r.path.endsWith('/grants')),'explicit refresh remains available while timer health pending');gate.resolve(value('health'));await promise;
 await setup();const blocked=await pending('refresh');const held=gate;const h=requests.filter(r=>r.path==='/health').length;$('project-select').value=other;await $('project-select').onchange();$('project-select').value=pid;await $('project-select').onchange();await tick();check(requests.filter(r=>r.path==='/health').length===h,'project ABA does not prematurely release timer latch');held.resolve([{id:'res_'+'4'.repeat(32),name:'PRIVATE_OLD',format:'txt',hash:'a'.repeat(64)}]);await blocked.promise;check(!$('materials').textContent.includes('PRIVATE_OLD'),'late old refresh cannot paint after project ABA');
 await setup();const identityOld=await pending('refresh'),identityHeld=gate;const identityHealth=requests.filter(r=>r.path==='/health').length;w.eval('clearIdentityView();token="synthetic-B";');w.eval('clearIdentityView();token="synthetic-A";');$('project-select').append(new w.Option('A',pid));$('project-select').value=pid;await tick();check(requests.filter(r=>r.path==='/health').length===identityHealth,'identity ABA does not release running background latch');identityHeld.resolve([{id:'res_'+'4'.repeat(32),name:'PRIVATE_IDENTITY',format:'txt',hash:'a'.repeat(64)}]);await identityOld.promise;check(!$('materials').textContent.includes('PRIVATE_IDENTITY'),'identity ABA late resource data cannot repaint');
 await setup();const old=await pending('showRun'),heldRun=gate;$('project-select').value=other;await $('project-select').onchange();$('project-select').value=pid;await $('project-select').onchange();heldRun.resolve({id:rid,status:'SUCCEEDED',namespace:'INTERNAL_APPRUN',version:1,events:[],result:{column:'PRIVATE_RUN',sum:'9',count:1}});await old.promise;check(!$('result').textContent.includes('PRIVATE_RUN')&&!$('raw-result').textContent,'late old run read cannot repaint cleared project context');
 await setup();$('goal').value='original intent';await w.submitOrdinaryRun();const body=JSON.stringify(requests.find(r=>r.method==='POST').body);check(w.runSubmissionEntry().state==='unknown','lost synthesized submission stays UNKNOWN');const postCount=requests.filter(r=>r.method==='POST').length;await tick();await tick();check(requests.filter(r=>r.method==='POST').length===postCount,'background polling issues zero submission retries/POST');$('goal').value='changed text';await $('run-submit-recover').onclick();check(JSON.stringify(requests.filter(r=>r.method==='POST')[1].body)===body,'explicit recovery preserves original UNKNOWN body/key');
 const result={status:'PASS',checks,source_sha256:crypto.createHash('sha256').update(fs.readFileSync(source)).digest('hex'),api:'SYNTHESIZED_NOT_HTTP',scheduler:'MANUAL_CALLBACK_2500MS_REGISTRATION',pg:'NOT_RUN',native:'NOT_RUN'};fs.writeFileSync(path.join(root,'results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
}catch(e){fs.writeFileSync(path.join(root,'failure.json'),JSON.stringify({status:'FAIL',checks,error:e.message,api:'SYNTHESIZED_NOT_HTTP'},null,2));console.error(e.stack);process.exitCode=1;}finally{dom?.window.close();}})();
