'use strict';
// Full production DOM/app.js/use.js; API and scheduler are synthesized, not HTTP/PG.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{JSDOM}=require('jsdom');
const out=process.argv[2],source=process.argv[3],web=path.join(__dirname,'../src/sim2act/web');
const pid='proj_'+'1'.repeat(32),other='proj_'+'2'.repeat(32),aid='app_'+'3'.repeat(32),iid='instance_'+'4'.repeat(32),fp='a'.repeat(64);
let dom,w,$,calls,hold;const checks=[];
const app={id:aid,project_id:pid,name:'CSV PRIVATE',fingerprint:fp,candidate:{manifest:{validation_suite_ref:'receipt.readback.v1',data_bindings:[{resource_ref:'res_private'}]},actions:[{executor:{kind:'registered_tool',ref:'data.aggregate_csv'}}]},input_guidance:{columns:[{name:'amount',numeric:true}]}};
const instance={id:iid,project_id:pid,source_app_id:aid,formal_publication_enabled:false,release_id:'release_fixed',release_fingerprint:fp,revision:1,data_version:0,runs:[],data:[]};
const release={project_id:pid,fingerprint:fp,snapshot:{draft:app,model_requests:0}};
const ok=(condition,label)=>{assert(condition,label);checks.push(label);};
const settle=()=>new Promise(r=>setImmediate(r));
function load(file){const s=w.document.createElement('script');s.textContent=fs.readFileSync(file,'utf8');w.document.body.append(s);}
async function setup(){dom?.window.close();dom=new JSDOM(fs.readFileSync(path.join(web,'index.html'),'utf8'),{url:'http://synthetic.invalid',runScripts:'dangerously'});w=dom.window;$=id=>w.document.getElementById(id);calls=[];hold=null;w.setInterval=(_,delay)=>{assert.equal(delay,2500);return 1;};w.crypto.randomUUID=()=>crypto.randomUUID();
 w.fetch=async(url,opts={})=>{calls.push({url,method:opts.method||'GET',body:opts.body&&JSON.parse(opts.body)});let data;
 if(hold&&!hold.used&&hold.url===url){hold.used=true;data=await new Promise((resolve,reject)=>Object.assign(hold,{resolve,reject}));}
 if(opts.method==='POST')throw Error('synthesized lost acceptance');
 if(data===undefined){if(url===`/api/apps/${aid}`)data=app;else if(url===`/api/internal/apps/${aid}/instances`)data={items:[instance]};else if(url===`/api/internal/instances/${iid}`)data=instance;else if(url==='/api/internal/releases/release_fixed')data=release;else if(url==='/api/apps'||url.endsWith('/goal-cards')||url.endsWith('/conditional-apps'))data={items:[]};else data=[];}
 return {ok:true,status:200,json:async()=>data};};load(path.join(web,'app.js'));load(source);$('project-select').append(new w.Option('A',pid),new w.Option('B',other));$('project-select').value=pid;w.eval('token="synthetic-A";');}
const summary=hint=>({id:aid,name:'summary',...(hint==='ABSENT'?{}:{csv_instance_candidate:hint})});
const count=url=>calls.filter(c=>c.url===url).length;
async function unknown(){await w.openApplicationUse(aid,iid);await w.submitApplicationUse(w.eval('applicationUse'));assert.equal(w.eval('applicationUseRequests.get(applicationUseKey(applicationUse)).state'),'unknown');return w.eval('JSON.stringify(applicationUseRequests.get(applicationUseKey(applicationUse)))');}
(async()=>{try{
 await setup();await w.refreshApplicationUse([summary(false)]);ok(calls.length===0,'strict false Report discovery sends zero inspect/instance requests');
 for(const hint of [true,'ABSENT',null,'false',0,{},[]]){await setup();await w.refreshApplicationUse([summary(hint)]);ok(count(`/api/apps/${aid}`)===1&&count(`/api/internal/apps/${aid}/instances`)===1,'CSV/unknown/malformed hint full inspect: '+JSON.stringify(hint));}
 for(const list of [[summary(false)],[]]){await setup();const saved=await unknown(),post=calls.filter(c=>c.method==='POST').length;for(const id of ['use-output','use-history','use-provenance','use-acceptance'])$(id).textContent='PRIVATE OLD';await w.refreshApplicationUse(list);ok(['use-output','use-history','use-provenance','use-acceptance','use-column'].every(id=>!$(id).textContent)&&$('use-form').hidden,'active CSV '+(list.length?'false':'absent')+' clears all protected data');ok(w.eval('JSON.stringify(applicationUseRequests.get(applicationUseKey(applicationUse)))')===saved&&!$('use-recover').hidden,'clear preserves exact UNKNOWN state/body/key and explicit recovery');ok(calls.filter(c=>c.method==='POST').length===post,'clear/discovery adds zero POST');}
 await setup();await w.refreshApplicationUse([summary(false)]);const before=calls.length;await w.openApplicationUse(aid,iid);ok(calls.length>before&&count(`/api/apps/${aid}`)===2&&!!w.eval('applicationUse.instance'),'explicit open still full source/release/current-app inspect');
 for(const identity of [false,true])for(const error of [false,true]){await setup();hold={url:`/api/apps/${aid}`,used:false};const pending=w.refreshApplicationUse([summary(true)]);while(!hold.used)await settle();const h=hold;
 if(identity){w.eval('clearIdentityView();token="synthetic-B";');w.eval('clearIdentityView();token="synthetic-A";');$('project-select').append(new w.Option('A',pid));$('project-select').value=pid;}else{$('project-select').value=other;w.clearApplicationUse(true);$('project-select').value=pid;w.clearApplicationUse(true);}
 $('use-list').textContent='CURRENT CLEAN';if(error)h.reject(Error('controlled old permission read error'));else h.resolve(app);await pending;
 ok($('use-list').textContent==='CURRENT CLEAN'&&count(`/api/internal/apps/${aid}/instances`)===0,(identity?'identity':'project')+' ABA late '+(error?'error':'data')+' cannot repaint/follow inspect');ok(calls.every(c=>c.method==='GET'),'ABA discovery issues zero POST');}
 await setup();await unknown();hold={url:`/api/apps/${aid}`,used:false};const pending=w.refreshApplicationUse([summary(true)]);while(!hold.used)await settle();const saved=w.eval('JSON.stringify(applicationUseRequests.get(applicationUseKey(applicationUse)))');hold.reject(Error('current permission failure'));await pending;ok($('use-form').hidden&&!$('use-provenance').textContent&&w.eval('JSON.stringify(applicationUseRequests.get(applicationUseKey(applicationUse)))')===saved,'current inspect error clears protected data while preserving UNKNOWN intent');
 const receipt={status:'PASS',checks,source_sha256:crypto.createHash('sha256').update(fs.readFileSync(source)).digest('hex'),app_sha256:crypto.createHash('sha256').update(fs.readFileSync(path.join(web,'app.js'))).digest('hex'),api:'SYNTHESIZED_NOT_HTTP',dom:'ACTUAL_FULL_INDEX',scheduler:'2500MS_REGISTERED_MANUAL_NOT_ELAPSED',pg:'NOT_RUN'};fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(receipt,null,2));console.log(JSON.stringify(receipt));
 }catch(e){fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({status:'FAIL',checks,error:e.message},null,2));console.error(e.stack);process.exitCode=1;}finally{dom?.window.close();}})();
