'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{JSDOM}=require('jsdom');
const root=process.argv[2],info=JSON.parse(fs.readFileSync(path.join(root,'info.json'))),checks=[],requests=[],hashes={};
let dom,w,$,mode='',release;
const check=(ok,label)=>{assert(ok,label);checks.push(label);};
const wait=async(fn,label)=>{const end=Date.now()+6000;while(Date.now()<end){if(fn())return;await new Promise(r=>setTimeout(r,10));}throw Error('Timeout '+label);};
async function setup(){
 dom?.window.close();const html=await(await fetch(info.base)).text();hashes['index.html']=crypto.createHash('sha256').update(html).digest('hex');
 dom=new JSDOM(html,{url:info.base,runScripts:'dangerously'});w=dom.window;$=id=>w.document.getElementById(id);
 w.fetch=async(url,opts={})=>{const target=new URL(url,info.base);assert.equal(target.origin,info.base,'no outbound HTTP');const entry={path:target.pathname,method:opts.method||'GET',body:opts.body&&JSON.parse(opts.body)};requests.push(entry);const response=await fetch(target,opts);
  if(mode==='bad-save'&&entry.path.endsWith('/conditional-apps')&&entry.method==='POST'){mode='';const bad=await response.json();delete bad.fingerprint;return {ok:true,json:async()=>bad};}
  if(mode==='bad-run'&&entry.path.includes('/conditional-apps/')&&entry.method==='POST'){mode='';const bad=await response.json();delete bad.phase;return {ok:true,json:async()=>bad};}
  if(mode==='hold-list'&&entry.path.endsWith('/conditional-apps')&&entry.method==='GET'){mode='';await new Promise(r=>release=r);release=null;}
  if(mode==='lost-save'&&entry.path.endsWith('/conditional-apps')&&entry.method==='POST'){mode='';throw TypeError('Synthetic lost accepted save receipt');}
  if(mode==='lost-run'&&entry.path.endsWith('/runs')&&entry.method==='POST'){mode='';throw TypeError('Synthetic lost accepted run receipt');}
  if(mode==='hold-history'&&entry.path.endsWith('/history')){mode='';await new Promise(r=>release=r);release=null;}
  if(mode==='hold-submit'&&entry.path.includes('/conditional-apps/')&&entry.method==='POST'){mode='';await new Promise(r=>release=r);release=null;}
  return response;};
 for(const name of ['app.js','internal.js','protocol.js','use.js','conditional-runs.js','conditional-apps.js']){const text=await(await fetch(info.base+'/'+name)).text();hashes[name]=crypto.createHash('sha256').update(text).digest('hex');const script=w.document.createElement('script');script.textContent=text;w.document.body.append(script);}
 $('token').value='synthetic-test-A';$('connect').click();await wait(()=>$('project-select').value===info.project&&$('login').hidden,'identity/project');await w.refreshReportApps();
}
function facts(prefix,amount,receipt=true){for(const[k,v]of Object.entries({trip:'true',receipt:String(receipt),approved:'false',amount:String(amount),days:'2'}))$(prefix+'-'+k).value=v;}
const work=async phase=>{const r=await fetch(info.base+'/test-only-report-worker/'+phase,{method:'POST',body:'{}',headers:{'Content-Type':'application/json'}});assert(r.ok,await r.text());};
(async()=>{try{
 await setup();await w.listConditionalSources();$('condition-resource').value=info.source;await w.openConditionalSource();facts('condition-run-source',680);await w.startBoundedSource();await work('source');await w.boundedAction(w.boundedRead);await w.extractBoundedCandidate();await work('extract');await w.boundedAction(w.boundedRead);
 check(!$('report-save-form').hidden,'sealed actual extraction enables named draft form');
 $('report-save-resource').value=info.fresh;$('report-save-name').value='Durable conditional Report';mode='lost-save';await w.saveReportDraft();check(!$('report-save-retry').hidden,'lost accepted save keeps manual same-key retry');mode='bad-save';await w.saveReportDraft(true);check(!$('report-save-retry').hidden&&$('report-save-submit').disabled,'malformed accepted save remains unknown and locked');await w.saveReportDraft(true);
 const saves=requests.filter(r=>r.path.endsWith('/conditional-apps')&&r.method==='POST');check(saves.length===3&&saves.every(r=>JSON.stringify(r.body)===JSON.stringify(saves[0].body)),'save recovery preserves exact body/key');
 const list=await (await fetch(info.base+`/api/projects/${info.project}/conditional-apps`,{headers:{Authorization:'Bearer synthetic-test-A'}})).json();const aid=list.items[0].id;
 check(list.items.length===1&&$('report-save-status').textContent.includes('PREVIEW_ONLY'),'one persistent named draft with preview boundary');
 await setup();check($('condition-run-plan').hidden&&$('report-app-list').textContent.includes('Durable conditional Report'),'fresh page lists durable draft without source-session plan');await w.openReportApp(aid);
 for(const [phase,amount,receipt]of [['allow',500,true],['block',680,false]]){facts('report-app',amount,receipt);if(phase==='allow')mode='lost-run';await w.runReportApp();if(phase==='allow'){check(!$('report-app-retry').hidden,'lost accepted cold receipt locks new intent');mode='bad-run';await w.runReportApp(true);check(!$('report-app-retry').hidden&&$('report-app-submit').disabled,'malformed accepted cold receipt remains unknown and locked');await w.runReportApp(true);}await work(phase);await w.readReportHistory();}
 check($('report-app-history').textContent.includes('ALLOW')&&$('report-app-history').textContent.includes('BLOCK'),'two new Scenario actual Reports differ in persisted history');
 const posts=requests.filter(r=>r.path.includes('/conditional-apps/')&&r.method==='POST');check(JSON.stringify(posts[0].body)===JSON.stringify(posts[1].body),'cold accepted receipt retry uses exact frozen key/body');check(posts.every(r=>Object.keys(r.body).sort().join(',')==='expected_app_fingerprint,request_key,scenario'),'user execution submits only typed Scenario and version/key');
 await setup();await w.openReportApp(aid);check($('report-app-history').textContent.includes('ALLOW')&&$('report-app-history').textContent.includes('BLOCK'),'second fresh page reloads actual two-Run history');facts('report-app',680);$('report-app-approved').value='';await w.runReportApp();await work('unknown');await w.readReportHistory();check($('report-app-history').textContent.includes('UNKNOWN'),'unknown typed facts do not reuse prior ALLOW answer');
 mode='hold-list';const staleList=w.refreshReportApps();await wait(()=>release,'held list');const listRelease=release;w.clearReportApps();$('project-select').value=info.other;$('project-select').value=info.project;listRelease();await staleList;check($('report-app-list').textContent==='','same-scope ABA cannot restore stale draft list');await w.openReportApp(aid);
 mode='hold-history';const held=w.readReportHistory();await wait(()=>release,'held history');$('project-select').value=info.other;$('project-select').dispatchEvent(new w.Event('change'));const resume=release;await wait(()=>$('report-app-form').hidden,'project cleared');resume();await held;check($('report-app-history').textContent==='','late history cannot restore cross-project result');
 $('project-select').value=info.project;$('project-select').dispatchEvent(new w.Event('change'));await w.refreshReportApps();await w.openReportApp(aid);facts('report-app',500);mode='hold-submit';const submitting=w.runReportApp();await wait(()=>release,'held submit');$('token').value='synthetic-test-B';$('connect').click();const resumeSubmit=release;await wait(()=>$('report-app-form').hidden,'identity cleared');resumeSubmit();await submitting;check($('report-app-output').textContent===''&&$('report-app-history').textContent==='','late accepted submit cannot restore another identity state');
 await setup();await w.openReportApp(aid);await fetch(info.base+'/test-only-report-revoke-target',{method:'POST',body:'{}',headers:{'Content-Type':'application/json'}});await assert.rejects(w.readReportHistory());check($('report-app-form').hidden&&$('report-app-history').textContent===''&&$('report-app-origin').textContent==='','actual revoked target read fails closed and clears protected Report');
 check(requests.filter(r=>r.path.includes('/conditional-apps')&&r.method==='POST').every(r=>!('candidate'in r.body)&&!('report'in r.body)&&!('gold'in r.body)&&!('runtime_id'in r.body)),'HTTP submissions exclude candidate/Report/gold/authority');
 const result={status:'PASS',checks,loaded_source_sha256:hashes,requests,requests_outside_origin:0,actual_mock_requests:6,live_requests:0,native:'NOT_RUN',semantic:'UNKNOWN',overall:'NOT_ACCEPTED'};fs.writeFileSync(path.join(root,'results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
}catch(e){console.error(e.stack);process.exitCode=1;}finally{dom?.window.close();}})();
