"use strict";
const fs=require("node:fs"),path=require("node:path"),assert=require("node:assert/strict"),crypto=require("node:crypto"),{JSDOM}=require("jsdom");
const root=process.argv[2],info=JSON.parse(fs.readFileSync(path.join(root,"info.json"))),checks=[],requests=[],assets=[];
let dom,w,page,drop=false,dropRead=false,hold=null,releaseHold=null;
const check=(value,label)=>{assert(value,label);checks.push(label);};
const wait=async fn=>{const until=Date.now()+10000;while(Date.now()<until){if(fn())return;await new Promise(r=>setTimeout(r,10));}throw Error("bounded DOM wait expired");};
async function idle(){await wait(()=>page.requests===0&&page.actions.size===0);await new Promise(r=>setImmediate(r));if(page.errors.length)throw page.errors[0];}
function track(window){for(const name of ["onclick","onchange","onsubmit"]){const d=Object.getOwnPropertyDescriptor(window.HTMLElement.prototype,name);Object.defineProperty(window.HTMLElement.prototype,name,{...d,set(fn){d.set.call(this,typeof fn==="function"?function(...args){const r=fn.apply(this,args);if(r&&typeof r.then==="function"){const action=Promise.resolve(r);page.actions.add(action);action.then(()=>page.actions.delete(action),e=>{page.actions.delete(action);page.errors.push(e);});}return r;}:fn);}});}window.addEventListener("error",e=>page.errors.push(e.error||Error(e.message)));}
async function boot(){const hashes={},html=await(await fetch(info.base)).text();hashes["index.html"]=crypto.createHash("sha256").update(html).digest("hex");dom=new JSDOM(html,{url:info.base,runScripts:"dangerously"});w=dom.window;page={requests:0,actions:new Set(),errors:[]};track(w);w.setInterval=()=>0;w.TextEncoder=TextEncoder;Object.defineProperty(w.crypto,"subtle",{value:crypto.webcrypto.subtle});w.crypto.randomUUID=()=>crypto.randomUUID();
w.fetch=async(url,opts={})=>{page.requests++;try{const target=new URL(url,info.base);assert.equal(target.origin,info.base);requests.push({path:target.pathname,method:opts.method||"GET",body:opts.body&&JSON.parse(opts.body),page:assets.length+1});const r=await fetch(target,opts);if(info.lost==="mint-post"&&target.pathname.endsWith("/csv-logic-authorizations")&&hold===null&&opts.method==="POST"){hold=true;await r.arrayBuffer();throw Error("owned fixture dropped mint response");}if(drop&&target.pathname.endsWith("/material-plans")&&opts.method==="POST"){drop=false;await r.arrayBuffer();throw Error("owned fixture dropped accepted response");}if(dropRead&&target.pathname.includes("/material-plans/")&&(opts.method||"GET")==="GET"){dropRead=false;await r.arrayBuffer();throw Error("owned fixture dropped GET after acceptance");}const bytes=await r.arrayBuffer();
if(target.pathname.endsWith("/material-plans")&&opts.method==="POST"){
  if(["late","identity-late"].includes(info.lost)&&!hold){hold=true;await new Promise(resolve=>{releaseHold=resolve;});}
  if(info.lost.startsWith("invalid")&&hold===null){hold=true;const m=JSON.parse(Buffer.from(bytes).toString());
 if(info.lost==="invalid")m.binding_fingerprint="0".repeat(64);
 else {if(info.lost==="invalid-key"){m.plan.request_key="logic-plan-"+"0".repeat(48);m.binding.plan_input.request_key=m.plan.request_key;m.binding_fingerprint=await w.deliveryDigest(m.binding);m.plan.logical_reuse.binding_fingerprint=m.binding_fingerprint;}
 else if(info.lost==="invalid-binding")m.plan.definition.manifest.data_bindings[0].resource_ref="res_"+"0".repeat(32);
 else m.plan.definition.manifest.runtime_limits.max_tools+=1;
 const {cached,plan_fingerprint,...v}=m.plan;m.plan.plan_fingerprint=await w.deliveryDigest(v);}
 return new Response(JSON.stringify(m),{status:201,headers:r.headers});}
}
return new Response(bytes,{status:r.status,headers:r.headers});}finally{page.requests--;}};
for(const name of Array.from(w.document.querySelectorAll("script[src]")).map(s=>s.getAttribute("src").slice(1))){const code=await(await fetch(info.base+"/"+name)).text();hashes[name]=crypto.createHash("sha256").update(code).digest("hex");const script=w.document.createElement("script");script.textContent=code;w.document.body.append(script);}const $=id=>w.document.getElementById(id);$("token").value="synthetic-test-A";$("connect").click();await wait(()=>$("login").hidden&&$("project-select").value===info.project);await idle();await w.showApp(info.app);assets.push({loaded_source_sha256:hashes});return $;}
async function work(rid){const response=await fetch(info.base+"/__fixture__/work",{method:"POST",headers:{Authorization:"Bearer synthetic-test-A","Content-Type":"application/json"},body:JSON.stringify({run_id:rid})});assert(response.ok,await response.text());}
(async()=>{try{
let $=await boot();$("dag-reuse-history").click();await idle();check($("dag-reuse-release").value===info.release,"source actual successful release restored");
$("csv-logic-authorize-confirm").checked=true;$("csv-logic-authorize-confirm").dispatchEvent(new w.Event("change"));$("csv-logic-authorize").click();await idle();
if(info.lost==="mint-post") {check($("csv-logic-status").textContent.includes("UNKNOWN"),"lost mint response preserves exact authorization intent");$("csv-logic-recover").click();await idle();}
const logic=JSON.parse($("csv-logic-proof").textContent);check(logic.status==="ACTIVE"&&logic.recipe.nodes.length===info.nodes,"explicit data-free authority before later material registration");
check(!JSON.stringify(logic).includes(info.resource)&&!JSON.stringify(logic).includes(info.release)&&!JSON.stringify(logic).includes('"amount"'),"public logic has no original resource, release or column");
$("resource-name").value="fresh-only.csv";$("format").value="csv";$("content").value="label,net,units\nfresh-A,-4.5,2\nfresh-B,12,7\nfresh-C,1.25,4\n";$("resource-form").dispatchEvent(new w.Event("submit",{cancelable:true}));await idle();
const list=await w.api(`/api/projects/${info.project}/resources`);info.targetresource=list.find(v=>v.name==="fresh-only.csv").id;
$("app-resource").value=info.targetresource;$("app-name").value="Independent fresh app";$("app-goal").value="New material only";$("app-form").dispatchEvent(new w.Event("submit",{cancelable:true}));await idle();info.targetapp=w.eval("activeApp");check(!!info.targetapp&&info.targetapp!==info.app,"actual page registers fresh CSV and existing registered app after authorization");
const retirement=await fetch(info.base+"/__fixture__/retire-old",{method:"POST",headers:{Authorization:"Bearer synthetic-test-A","Content-Type":"application/json"},body:"{}"});check(retirement.ok,"owned old user/runtime grants revoked and synthetic original CSV deleted");
$("delivery-derive").click();await idle();check(!$("error").textContent,"target alone derives current post-revocation graph without rerunning source");
const old=await fetch(info.base+`/api/internal/releases/${info.release}`,{headers:{Authorization:"Bearer synthetic-test-A"}});check(old.status!==200,"original release still denied after deletion");
const start=requests.length;$("csv-logic-history").click();await idle();$("csv-logic-options").click();await idle();check($("csv-logic-target").options.length===1&&$("csv-logic-target").value===info.targetapp,"global project entry offers only current authorized target without reading old source");check(!requests.slice(start).some(r=>r.path.includes(info.app)||r.path.includes(info.resource)||r.path.includes(info.release)),"logic restore/options never GET original app, resource or release");
check($("csv-logic-plan").disabled,"target plan needs independent explicit confirmation");$("csv-logic-column").value="net";$("csv-logic-column").dispatchEvent(new w.Event("change"));$("csv-logic-confirm").checked=true;$("csv-logic-confirm").dispatchEvent(new w.Event("change"));
drop=["post","unknown403"].includes(info.lost);dropRead=info.lost==="read";$("csv-logic-plan").click();
if(["late","identity-late"].includes(info.lost)){await wait(()=>!!releaseHold);if(info.lost==="identity-late"){$("token").value="synthetic-test-B";$("connect").click();await wait(()=>$("project-select").options.length===0);await new Promise(r=>setTimeout(r,20));check(!$("csv-logic-proof").textContent,"identity change clears old target proof");$("token").value="synthetic-test-A";$("connect").click();await wait(()=>$("project-select").value===info.project);}await w.showApp(info.targetapp);await w.showApp(info.targetapp);await wait(()=>page.requests===1&&page.actions.size===1);const lateStart=requests.length;releaseHold();await idle();check(requests.length===lateStart,"late acceptance pure-seals frozen target without identity-dependent follow-up requests");check(!$("csv-logic-proof").textContent&&!$("csv-logic-recover").hidden,"late ABA accepts to frozen intent without painting replacement selection");}
else {await idle();if(info.lost!=="mint-post")check($("csv-logic-status").textContent.includes("UNKNOWN")&&$("csv-logic-target").disabled,"lost or corrupt response keeps frozen target intent UNKNOWN");}
const mutationPosts=()=>requests.filter(r=>r.method==="POST"&&r.path.endsWith("/material-plans"));
if(info.lost==="unknown403"){const admin=async revoked=>{const r=await fetch(info.base+"/__fixture__/target-grant",{method:"POST",headers:{Authorization:"Bearer synthetic-test-A","Content-Type":"application/json"},body:JSON.stringify({resource_id:info.targetresource,app_id:info.targetapp,revoked})});assert(r.ok);};await admin(true);$("csv-logic-recover").click();await idle();check($("csv-logic-status").textContent.includes("UNKNOWN")&&$("csv-logic-target").disabled,"UNKNOWN retry403 cannot rebind target or lose original key");await admin(false);}
if(info.lost!=="mint-post"){$("csv-logic-recover").click();await idle();}
const posts=mutationPosts();check(posts.length===(["read","late","identity-late","mint-post"].includes(info.lost)?1:info.lost==="unknown403"?3:2),"known read failure or late acceptance retries GET only; unknown repeats same POST");check(posts.every(v=>JSON.stringify(v.body)===JSON.stringify(posts[0].body)),"all unknown target retries preserve complete exact body and key");
const m=JSON.parse($("csv-logic-proof").textContent);check(m.binding.target.resource_id===info.targetresource&&m.binding.column==="net"&&m.plan.composition.definition.nodes.length===info.nodes,"verified new target plan binds canonical closed family and actual independent bytes");check(!requests.some(r=>r.method==="POST"&&r.path.endsWith("/runs")),"mint/target plan creates no execution or typed result");
$("csv-logic-open").click();await idle();check($("csv-dag-run").disabled&&!$("csv-dag-confirm").checked,"open requires separate actual execution confirmation");$("csv-dag-confirm").checked=true;$("csv-dag-confirm").dispatchEvent(new w.Event("change"));$("csv-dag-run").click();await idle();let job=JSON.parse($("csv-dag-result").textContent);await work(job.id);$("csv-dag-refresh").click();await idle();job=JSON.parse($("csv-dag-result").textContent);const output=Object.values(job.result.output_by_step)[0];check(job.status==="SUCCEEDED"&&job.steps.length===info.nodes&&output.resource_id===info.targetresource&&output.sum==="8.75"&&output.count===3,"actual existing worker executes solely new target and returns independent8.75/count3");
$("dag-reuse-prepare").click();await idle();$("dag-reuse-confirm").checked=true;$("dag-reuse-confirm").dispatchEvent(new w.Event("change"));$("dag-reuse-commit").click();await idle();$("dag-reuse-create").click();await idle();const iid=$("dag-reuse-instance").value;check(!!iid,"new target version and instance require separate original confirmations");
const coldStart=requests.length;dom.window.close();info.app=info.targetapp;$=await boot();$("csv-logic-history").click();await idle();$("dag-reuse-history").click();await idle();$("dag-reuse-instance").value=iid;$("dag-reuse-read").click();await idle();check(requests.slice(coldStart).every(r=>r.method==="GET"),"second cold page restores logic and target instance using GET only");$("dag-reuse-column").value="units";$("dag-reuse-column").dispatchEvent(new w.Event("change"));$("dag-reuse-run-confirm").checked=true;$("dag-reuse-run-confirm").dispatchEvent(new w.Event("change"));$("dag-reuse-run").click();await idle();let d=JSON.parse($("dag-reuse-proof").textContent).instance;await work(d.runs[0].run_id);$("dag-reuse-read").click();await idle();d=JSON.parse($("dag-reuse-proof").textContent).instance;check(d.data_version===1&&d.data[0].data.result.sum==="13"&&d.data[0].data.result.count===3&&d.data[0].data.result.resource_id===info.targetresource,"cold changed-column instance inherits logic and writes fresh13/count3");
$("csv-logic-history").click();await idle();$("csv-logic-revoke-confirm").checked=true;$("csv-logic-revoke-confirm").dispatchEvent(new w.Event("change"));$("csv-logic-revoke").click();await idle();check(JSON.parse($("csv-logic-proof").textContent).status==="REVOKED","independent owner control revokes after old data deleted");const revoked=await fetch(info.base+`/api/internal/instances/${iid}`,{headers:{Authorization:"Bearer synthetic-test-A"}});check(revoked.status!==200,"revoked logical origin denies target instance historical result and further reuse");
fs.writeFileSync(path.join(root,"results.json"),JSON.stringify({status:"PASS",pages:2,checks,requests,assets,logic,plan:m,instance:d},null,2));console.log(JSON.stringify({status:"PASS",pages:2,checks:checks.length}));
}catch(e){fs.writeFileSync(path.join(root,"FAILURE.json"),JSON.stringify({message:String(e),checks,requests,assets,html:dom?.serialize()},null,2));console.error(e);process.exitCode=1;}finally{dom?.window.close();}})();
