"use strict";
const fs=require("node:fs"),path=require("node:path"),assert=require("node:assert/strict"),crypto=require("node:crypto"),{JSDOM}=require("jsdom");
const root=process.argv[2],info=JSON.parse(fs.readFileSync(path.join(root,"info.json"))),checks=[],requests=[],assets=[];
let dom,w,page,drop=false,dropRead=false;
const check=(value,label)=>{assert(value,label);checks.push(label);};
const wait=async fn=>{const until=Date.now()+10000;while(Date.now()<until){if(fn())return;await new Promise(r=>setTimeout(r,10));}throw Error("bounded DOM wait expired");};
async function idle(){await wait(()=>page.requests===0&&page.actions.size===0);await new Promise(r=>setImmediate(r));if(page.errors.length)throw page.errors[0];}
function track(window){for(const name of ["onclick","onchange","onsubmit"]){const d=Object.getOwnPropertyDescriptor(window.HTMLElement.prototype,name);Object.defineProperty(window.HTMLElement.prototype,name,{...d,set(fn){d.set.call(this,typeof fn==="function"?function(...args){const r=fn.apply(this,args);if(r&&typeof r.then==="function"){const action=Promise.resolve(r);page.actions.add(action);action.then(()=>page.actions.delete(action),e=>{page.actions.delete(action);page.errors.push(e);});}return r;}:fn);}});}window.addEventListener("error",e=>page.errors.push(e.error||Error(e.message)));}
async function boot(){const hashes={},html=await(await fetch(info.base)).text();hashes["index.html"]=crypto.createHash("sha256").update(html).digest("hex");dom=new JSDOM(html,{url:info.base,runScripts:"dangerously"});w=dom.window;page={requests:0,actions:new Set(),errors:[]};track(w);w.setInterval=()=>0;w.TextEncoder=TextEncoder;Object.defineProperty(w.crypto,"subtle",{value:crypto.webcrypto.subtle});w.crypto.randomUUID=()=>crypto.randomUUID();
w.fetch=async(url,opts={})=>{page.requests++;try{const target=new URL(url,info.base);assert.equal(target.origin,info.base);requests.push({path:target.pathname,method:opts.method||"GET",body:opts.body&&JSON.parse(opts.body),page:assets.length+1});const r=await fetch(target,opts);if(drop&&target.pathname.includes("/api/internal/instances/")&&target.pathname.endsWith("/runs")&&opts.method==="POST"){drop=false;await r.arrayBuffer();throw Error("owned fixture dropped accepted response");}if(dropRead&&target.pathname.includes("/api/internal/instances/")&&target.pathname.includes("/runs/")&&(opts.method||"GET")==="GET"){dropRead=false;await r.arrayBuffer();throw Error("owned fixture dropped GET after acceptance");}return new Response(await r.arrayBuffer(),{status:r.status,headers:r.headers});}finally{page.requests--;}};
for(const name of Array.from(w.document.querySelectorAll("script[src]")).map(s=>s.getAttribute("src").slice(1))){const code=await(await fetch(info.base+"/"+name)).text();hashes[name]=crypto.createHash("sha256").update(code).digest("hex");const script=w.document.createElement("script");script.textContent=code;w.document.body.append(script);}const $=id=>w.document.getElementById(id);$("token").value="synthetic-test-A";$("connect").click();await wait(()=>$("login").hidden&&$("project-select").value===info.project);await idle();await w.showApp(info.app);assets.push({loaded_source_sha256:hashes});return $;}
async function work(rid){const response=await fetch(info.base+"/__fixture__/work",{method:"POST",headers:{Authorization:"Bearer synthetic-test-A","Content-Type":"application/json"},body:JSON.stringify({run_id:rid})});assert(response.ok,await response.text());}
(async()=>{try{
let $=await boot();check($("dag-reuse-prepare").disabled,"unselected source cannot prepare a version");await w.csvDagRead(undefined,info.source,info.plan);check(!$("dag-reuse-prepare").disabled,"all real verified source nodes enable reuse");
$("dag-reuse-prepare").click();await idle();check($("dag-reuse-commit").disabled&&!$("dag-reuse-confirm").checked,"preparation has no automatic version commit");const approval=JSON.parse($("dag-reuse-proof").textContent);check(approval.payload.snapshot.execution_source.run_id===info.source&&approval.payload.snapshot.execution_source.receipt_fingerprints.length===info.nodes,"approval binds actual source run and all receipts");
$("dag-reuse-confirm").checked=true;$("dag-reuse-confirm").dispatchEvent(new w.Event("change"));$("dag-reuse-commit").click();await idle();check($("dag-reuse-release").options.length===1&&$("dag-reuse-instance").options.length===0,"explicit commit produces a version without implicit instance");
$("dag-reuse-create").click();await idle();const iid=$("dag-reuse-instance").value;check(!!iid&&$("dag-reuse-column").options.length===2,"separate instance exposes frozen numeric columns");check($("dag-reuse-run").disabled,"new run requires separate confirmation");
$("dag-reuse-column").value="quantity";$("dag-reuse-column").dispatchEvent(new w.Event("change"));$("dag-reuse-run-confirm").checked=true;$("dag-reuse-run-confirm").dispatchEvent(new w.Event("change"));drop=info.lost==="post";dropRead=info.lost==="read";$("dag-reuse-run").click();await idle();
check($("dag-reuse-status").textContent.includes("UNKNOWN")&&$("dag-reuse-run").disabled,"lost acceptance or read retains frozen intent");const before=requests.filter(r=>r.method==="POST"&&r.path===`/api/internal/instances/${iid}/runs`).length;$("dag-reuse-recover").click();await idle();const posts=requests.filter(r=>r.method==="POST"&&r.path===`/api/internal/instances/${iid}/runs`);check(posts.length===(info.lost==="post"?2:before),"known acceptance recovers via GET; unknown POST repeats same idempotent key");if(info.lost==="post")check(JSON.stringify(posts[0].body)===JSON.stringify(posts[1].body),"unknown POST recovery preserves exact full body");else check(posts.length===1,"accepted read failure never issues another POST");
let detail=JSON.parse($("dag-reuse-proof").textContent).instance;check(detail.runs.length===1&&detail.runs[0].status==="QUEUED"&&detail.data_version===0,"accepted new run does not copy source result");const first=detail.runs[0].run_id;await work(first);$("dag-reuse-read").click();await idle();detail=JSON.parse($("dag-reuse-proof").textContent).instance;check(detail.data_version===1&&detail.data[0].data.result.sum==="15"&&detail.runs[0].proof.steps.length===info.nodes,"worker performs actual new-column read and aggregate before typed append");if(info.nodes===3){const r=detail.runs[0];check(r.execution_version==="internal.csv-read-sum-report.v1"&&r.proof.result.output_by_step.formatted.text==="列 quantity；行数 2；合计 15"&&!Object.hasOwn(r.output,"text"),"three actual operations retain report sink and exact five-field typed result");}check(detail.runs[0].proof.business_writes===1&&detail.runs[0].proof.model_requests===0&&detail.runs[0].proof.owner_acceptance==="PENDING","typed write counted without changing acceptance boundaries");
const beforeCold=requests.length;dom.window.close();$=await boot();$("dag-reuse-history").click();await idle();$("dag-reuse-instance").value=iid;$("dag-reuse-read").click();await idle();check(requests.slice(beforeCold).every(r=>r.method==="GET"),"fresh cold page restores history and checked results with zero POST");detail=JSON.parse($("dag-reuse-proof").textContent).instance;check(detail.data_version===1&&detail.runs[0].run_id===first,"cold state retains actual first run lineage");
$("dag-reuse-column").value="amount";$("dag-reuse-column").dispatchEvent(new w.Event("change"));check($("dag-reuse-run").disabled,"cold changed input resets confirmation");$("dag-reuse-run-confirm").checked=true;$("dag-reuse-run-confirm").dispatchEvent(new w.Event("change"));$("dag-reuse-run").click();await idle();detail=JSON.parse($("dag-reuse-proof").textContent).instance;const second=detail.runs.find(v=>v.status==="QUEUED").run_id;check(second!==first&&second!==info.source,"cold new input allocates independent run");await work(second);$("dag-reuse-read").click();await idle();detail=JSON.parse($("dag-reuse-proof").textContent).instance;check(detail.data_version===2&&detail.data.map(v=>v.data.result.sum).join(",")==="15,30","cold new column produces second actual typed result version");
fs.writeFileSync(path.join(root,"results.json"),JSON.stringify({status:"PASS",pages:2,checks,requests,assets,instance:detail},null,2));console.log(JSON.stringify({status:"PASS",pages:2,checks:checks.length}));
}catch(e){fs.writeFileSync(path.join(root,"FAILURE.json"),JSON.stringify({message:String(e),checks,requests,assets,html:dom?.serialize()},null,2));console.error(e);process.exitCode=1;}finally{dom?.window.close();}})();
