'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{JSDOM}=require('jsdom');
const root=process.argv[2],info=JSON.parse(fs.readFileSync(path.join(root,'info.json'))),checks=[],requests=[],hashes={};let dom,w,$,mode='',release,page;const lifecycle=[];const started=Date.now();
const check=(v,label)=>{assert(v,label);checks.push(label);console.log(JSON.stringify({check:checks.length,label,elapsed_ms:Date.now()-started}));};
const wait=async fn=>{const end=Date.now()+6000;while(Date.now()<end){if(fn())return;await new Promise(r=>setTimeout(r,10));}throw Error('bounded wait expired');};
async function idlePage(){
 if(!page)return;
 await wait(()=>page.requests===0&&page.actions.size===0,'page actions and HTTP drained');
 await new Promise(resolve=>setImmediate(resolve));
 if(page.errors.length)throw page.errors[0];
 assert.equal(page.requests,0);assert.equal(page.actions.size,0);
}
async function closePage(){
 if(!dom)return;
 await idlePage();
 lifecycle.push({requests:page.requests,actions:page.actions.size,errors:page.errors.length});
 dom.window.close();dom=null;
}
function trackHandlers(window,current){
 for(const name of ['onclick','onchange','onsubmit']){
  const descriptor=Object.getOwnPropertyDescriptor(window.HTMLElement.prototype,name);
  assert(descriptor?.set,'JSDOM handler descriptor required');
  Object.defineProperty(window.HTMLElement.prototype,name,{...descriptor,set(fn){
   descriptor.set.call(this,typeof fn==='function'?function(...args){
    const result=fn.apply(this,args);
    if(result&&typeof result.then==='function'){
     const action=Promise.resolve(result);current.actions.add(action);
     action.then(()=>current.actions.delete(action),error=>{current.errors.push(error);current.actions.delete(action);});
    }
    return result;
   }:fn);
  }});
 }
 window.addEventListener('error',event=>{current.errors.push(event.error||Error(event.message));});
}
async function setup(){await closePage();const html=await(await fetch(info.base)).text();hashes['index.html']=crypto.createHash('sha256').update(html).digest('hex');dom=new JSDOM(html,{url:info.base,runScripts:'dangerously'});w=dom.window;$=id=>w.document.getElementById(id);page={requests:0,actions:new Set(),errors:[]};trackHandlers(w,page);w.setInterval=()=>0;const current=page;w.TextEncoder=TextEncoder;Object.defineProperty(w.crypto,'subtle',{value:crypto.webcrypto.subtle});w.crypto.randomUUID=()=>crypto.randomUUID();
 w.fetch=async(url,opts={})=>{current.requests++;try{const target=new URL(url,info.base);assert.equal(target.origin,info.base);const r={path:target.pathname,method:opts.method||'GET',body:opts.body&&JSON.parse(opts.body)};requests.push(r);if(mode==='later422'&&r.method==='POST'){mode='';return{ok:false,status:422,json:async()=>({error:{code:'INVALID_MANIFEST'}})};}if(mode==='first422'&&r.method==='POST'&&r.path.endsWith('/plans')){mode='';opts={...opts,body:JSON.stringify({...r.body,unexpected:true})};}const response=await fetch(target,opts);
 if(mode==='lost'&&r.method==='POST'&&r.path.includes('/delivery-graph/')){mode='';throw Error('controlled lost accepted response');}
 if(mode==='hold'&&r.path.endsWith('/delivery-graph')&&r.method==='GET'){mode='';await new Promise(r=>release=r);release=null;}
 if(mode==='bad-derive'&&r.method==='POST'&&r.path.endsWith('/derive')){mode='';const d=await response.json();d.candidate_fingerprint='0'.repeat(64);return{ok:true,status:201,json:async()=>d};}
 if(mode==='wrong-source-versions'&&r.path.endsWith('/delivery-graph')){mode='';const d=await response.json();d.source_versions[Object.keys(d.source_versions)[0]].content_fingerprint='0'.repeat(64);return{ok:true,status:200,json:async()=>d};}
 if(mode==='wrong-graph'&&r.path.endsWith('/delivery-graph')){mode='';const d=await response.json();d.graph.nodes[0].revision++;return{ok:true,status:200,json:async()=>d};}
 if(mode==='wrong-plan'&&r.method==='POST'&&r.path.endsWith('/plans')){mode='';const d=await response.json();d.receipt.project_id=info.other;return{ok:true,status:201,json:async()=>d};}
 if(mode==='wrong-history'&&r.method==='GET'&&r.path.endsWith('/plans')){mode='';const d=await response.json();d.items[0].receipt.changed_nodes=['node_'+'0'.repeat(32)];return{ok:true,status:200,json:async()=>d};}
 const bytes=await response.arrayBuffer();return new Response(bytes,{status:response.status,headers:response.headers});}finally{current.requests--;}};
 for(const name of ['app.js','internal.js','protocol.js','use.js','conditional-runs.js','conditional-apps.js','report-manifest.js','delivery-graph.js']){const code=await(await fetch(info.base+'/'+name)).text();hashes[name]=crypto.createHash('sha256').update(code).digest('hex');const s=w.document.createElement('script');s.textContent=code;w.document.body.append(s);}
 $('token').value='synthetic-test-A';$('connect').click();await wait(()=>$('project-select').value===info.project&&$('login').hidden);await idlePage();await w.showApp(info.app);
}
(async()=>{try{await setup();check(!$('delivery-panel').hidden&&requests.filter(r=>r.method==='POST').length===0,'opening generic app does not derive or plan');await w.readDeliveryGraph();check($('delivery-status').textContent.includes('尚未保存')&&!$('delivery-proof').textContent,'exact no-anchor read is empty without fake failure evidence');mode='lost';await w.submitDeliveryGraph('derive');check(!$('delivery-retry').hidden&&$('delivery-derive').disabled,'lost accepted anchor retains immutable key');const first=requests.filter(r=>r.path.endsWith('/derive'))[0];mode='bad-derive';await w.submitDeliveryGraph(null,true);check(!$('delivery-retry').hidden&&!$('delivery-proof').textContent,'malformed accepted anchor binding preserves key and clears evidence');mode='later422';await w.submitDeliveryGraph(null,true);check(!$('delivery-retry').hidden,'later422 cannot discard earlier unknown acceptance');await w.submitDeliveryGraph(null,true);const derives=requests.filter(r=>r.path.endsWith('/derive'));check(derives.every(r=>JSON.stringify(r.body)===JSON.stringify(first.body)),'derive recovery uses exact same body/key');check($('delivery-retry').hidden&&$('delivery-proof').textContent.includes('delivery-graph.v1'),'derive accepted only after full saved graph readback');check($('delivery-status').textContent.includes('UNKNOWN')&&$('delivery-status').textContent.includes('未执行'),'graph is planning UNKNOWN/PENDING without execution claim');
 const pick=()=>{$('delivery-nodes').querySelector('input').checked=true;};pick();mode='first422';await w.submitDeliveryGraph('plans');check($('delivery-retry').hidden&&$('delivery-status').textContent.includes('被拒绝'),'actual first422 rejection frees first unaccepted intent');await w.readDeliveryGraph();pick();mode='wrong-plan';await w.submitDeliveryGraph('plans');check(!$('delivery-retry').hidden&&!$('delivery-plans').textContent,'crossproject receipt clears evidence and retains key');await w.submitDeliveryGraph(null,true);check($('delivery-retry').hidden&&$('delivery-plans').textContent.includes('未执行'),'samekey recovery reads persisted scope plan');check(info.family==='REPORT'?$('delivery-plans').textContent.includes('BLOCKED_PARTIAL')&&$('delivery-plans').textContent.includes('GRAPH_NOT_DERIVED'):$('delivery-plans').textContent.includes('PENDING'),'actual expansion clearly distinguishes missing peer graph from pending scope');const posts=requests.filter(r=>r.method==='POST'&&r.path.endsWith('/plans')).slice(-2);check(JSON.stringify(posts[0].body)===JSON.stringify(posts[1].body),'planning retry preserves selected node revisions and fingerprints');const auth={Authorization:'Bearer synthetic-test-A','Content-Type':'application/json'};const nodeStale=structuredClone(posts[0].body);nodeStale.request_key='independent-stale-node';nodeStale.changes[0].expected_revision++;const stale=await fetch(info.base+posts[0].path,{method:'POST',headers:auth,body:JSON.stringify(nodeStale)});check(stale.status===409,'actual stale node version is rejected without plan');const different=structuredClone(posts[0].body);different.changes[0].expected_content_fingerprint='0'.repeat(64);const conflict=await fetch(info.base+posts[0].path,{method:'POST',headers:auth,body:JSON.stringify(different)});check(conflict.status===409,'samekey different node fingerprint is rejected');check($('delivery-plans').textContent.includes('patch_executed')&&$('delivery-plans').textContent.includes('false'),'actual scope receipt explicitly disables patch/publication');
 mode='wrong-history';await w.readDeliveryGraph();check(!$('delivery-proof').textContent&&!$('delivery-plans').textContent,'tampered history cannot leave prior protected graph evidence');await w.readDeliveryGraph();mode='wrong-graph';await w.readDeliveryGraph();check(!$('delivery-proof').textContent&&!$('delivery-plans').textContent,'altered graph node revision without canonical seal is rejected');await w.readDeliveryGraph();
 mode='hold';const p=w.readDeliveryGraph();await wait(()=>release);const resume=release;$('project-select').value=info.other;w.clearApp();$('project-select').value=info.project;await w.showApp(info.app);resume();await p;check(!$('delivery-proof').textContent&&!$('delivery-plans').textContent,'project ABA late graph read cannot restore old evidence');await w.readDeliveryGraph();check($('delivery-proof').textContent,'fresh explicit graph read works after ABA');mode='hold';const identityABA=w.readDeliveryGraph();await wait(()=>release);const resumeIdentity=release;$('token').value='synthetic-test-B';$('connect').click();await wait(()=>w.eval('token')==='synthetic-test-B'&&$('project-select').value==='');$('token').value='synthetic-test-A';$('connect').click();await wait(()=>w.eval('token')==='synthetic-test-A'&&$('project-select').value===info.project);await w.showApp(info.app);resumeIdentity();await identityABA;check(!$('delivery-proof').textContent&&!$('delivery-plans').textContent,'actual identity ABA cannot revive late graph evidence');
 await setup();mode='wrong-source-versions';await w.readDeliveryGraph();check(!$('delivery-proof').textContent&&!$('delivery-plans').textContent,'fresh page source-version tamper fails actual context seal');await w.readDeliveryGraph();check($('delivery-plans').textContent.includes('影响规划'),'fresh HTTP page reads actual durable graph and plan history');mode='hold';const q=w.readDeliveryGraph();await wait(()=>release);const identityResume=release;$('token').value='synthetic-test-B';$('connect').click();await wait(()=>$('delivery-panel').hidden);identityResume();await q;check(!$('delivery-proof').textContent&&!$('delivery-plans').textContent,'identity change clears protected graph despite late response');await assert.rejects(w.showApp(info.app));check($('delivery-panel').hidden,'actual unauthorized identity cannot open app graph');
 const response=await fetch(info.base+`/api/projects/${info.other}/apps/${info.app}/delivery-graph`,{headers:{Authorization:'Bearer synthetic-test-A'}});check([403,404].includes(response.status),'actual wrong project rejects graph access');await setup();await w.readDeliveryGraph();const revoked=await fetch(info.base+`/api/grants/${info.revoke.id}/revoke`,{method:'POST',headers:{Authorization:'Bearer synthetic-test-A','Content-Type':'application/json'},body:JSON.stringify({command:'revoke',version:info.revoke.version})});check(revoked.ok,'actual owner revokes one pre-existing fixture grant');await w.readDeliveryGraph();check(!$('delivery-proof').textContent&&!$('delivery-plans').textContent&&!$('delivery-nodes').textContent,'actual source revocation clears current graph/planning evidence');check(requests.filter(r=>r.method==='POST').every(r=>Object.keys(r.body).every(k=>['expected_candidate_fingerprint','request_key','expected_graph_fingerprint','changes'].includes(k))),'closed UI sends no graph/authority/context/provider');const result={status:'PASS',checks,loaded_source_sha256:hashes,requests,live_requests:0,native:'NOT_RUN',semantic:'UNKNOWN',publication:false};fs.writeFileSync(path.join(root,'results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));}catch(e){fs.writeFileSync(path.join(root,'failure.json'),JSON.stringify({status:'FAIL',checks,error:e.message,requests,loaded_source_sha256:hashes},null,2));console.error(e.stack);process.exitCode=1;}finally{await closePage();}})();
