'use strict';
// Real full DOM/app.js; controlled API replies, no HTTP/worker or native claim.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{JSDOM}=require('jsdom');
const out=process.argv[2],web=path.join(__dirname,'../src/sim2act/web'),pid='proj_'+'1'.repeat(32),other='proj_'+'2'.repeat(32),cid='goal_'+'3'.repeat(32),rid='run_'+'4'.repeat(32),fp='a'.repeat(64);
let dom,w,$,calls,postMode,readMode,hold;const checks=[];
const card={id:cid,project_id:pid,version:1,fingerprint:fp,content:{title:'saved',goal:'SAVED',known:['known'],assumptions:['assumption'],unresolved:['question'],constraints:['hard'],acceptance_checks:['check'],resource_refs:[]},history:[]};
card.history=[{version:1,fingerprint:fp,snapshot:{schema_version:'F2-goal-card.v1',content:card.content,resource_snapshots:[]}}];
const receipt={run_id:rid,status:'ACCEPTED',goal_card_id:cid,goal_version:1,goal_fingerprint:fp,goal_acceptance:'NOT_RUN',candidate_generated:false};
const run={id:rid,status:'PARTIAL',version:1,events:[],contract:{snapshot:{source_goal_card:{card_id:cid,version:1,fingerprint:fp,snapshot:{schema_version:'F2-goal-card.v1',content:card.content,resource_snapshots:[]}}}},result:{mode:'MOCK',receipts:[{data:{content:'ACTUAL SYNTHETIC RESULT'}}]}};
const check=(v,n)=>{assert(v,n);checks.push(n);};
const settle=()=>new Promise(r=>setImmediate(r));
async function setup(){dom?.window.close();dom=new JSDOM(fs.readFileSync(path.join(web,'index.html'),'utf8'),{url:'http://synthetic.invalid',runScripts:'dangerously'});w=dom.window;$=id=>w.document.getElementById(id);calls=[];postMode='ok';readMode='ok';hold=null;w.setInterval=(_,delay)=>{assert.equal(delay,2500);return 1;};w.crypto.randomUUID=()=>crypto.randomUUID();
 w.fetch=async(url,opts={})=>{const method=opts.method||'GET';calls.push({url,method,body:opts.body&&JSON.parse(opts.body)});let value,status=200;
 if(hold&&!hold.used&&hold.url===url){hold.used=true;value=await new Promise((resolve,reject)=>Object.assign(hold,{resolve,reject}));}
 if(value===undefined){if(method==='POST'){if(postMode==='lost')throw Error('controlled lost receipt');if(postMode==='422')return {ok:false,status:422,json:async()=>({error:{code:'INVALID_INPUT'}})};value=postMode==='bad'?{...receipt,goal_fingerprint:'b'.repeat(64)}:receipt;}
 else if(url===`/api/goal-cards/${cid}`)value=card;else if(url===`/api/runs/${rid}`){if(readMode==='error')throw Error('controlled read failure');value=readMode==='wrong'?{...run,contract:{snapshot:{source_goal_card:{...run.contract.snapshot.source_goal_card,card_id:'goal_wrong'}}}}:readMode==='wrongSnapshot'?{...run,contract:{snapshot:{source_goal_card:{...run.contract.snapshot.source_goal_card,snapshot:{...run.contract.snapshot.source_goal_card.snapshot,content:{...card.content,constraints:['TAMPERED']}}}}}}:run;}else if(url.endsWith('/candidate-options'))value={options:[]};else if(url.endsWith('/candidates')||url==='/api/apps'||url.endsWith('/goal-cards')||url.endsWith('/conditional-apps'))value={items:[]};else value=[];}
 return {ok:status===200,status,json:async()=>value};};const s=w.document.createElement('script');s.textContent=fs.readFileSync(path.join(web,'app.js'),'utf8');w.document.body.append(s);$('project-select').append(new w.Option('A',pid),new w.Option('B',other));$('project-select').value=pid;w.eval('token="synthetic-A"');await w.showGoalCard(cid);}
const entry=()=>w.eval('goalRunRequests.get(goalRunKey())');const posts=()=>calls.filter(x=>x.method==='POST');
async function actualHttp(){
 const info=JSON.parse(fs.readFileSync(path.join(out,'info.json'))),loaded={};
 async function page(){dom?.window.close();const html=await(await fetch(info.base)).text();dom=new JSDOM(html,{url:info.base,runScripts:'dangerously'});w=dom.window;$=id=>w.document.getElementById(id);w.crypto.randomUUID=()=>crypto.randomUUID();
  w.fetch=(url,opts={})=>{const target=new URL(url,info.base);assert.equal(target.origin,info.base);return fetch(target,opts);};
  const response=await fetch(info.base+'/app.js'),code=await response.text();loaded['app.js']=crypto.createHash('sha256').update(code).digest('hex');const script=w.document.createElement('script');script.textContent=code;w.document.body.append(script);
  $('project-select').append(new w.Option('Project',info.project));$('project-select').value=info.project;w.eval('token="synthetic-test-A"');
 }
 await page();await w.refresh();await w.showGoalCard(info.card);check(!$('goal-card-run').disabled,'HTTP saved card enables explicit execution');$('goal-card-goal').value='UNSAVED MUST NOT EXECUTE';await $('goal-card-run').onclick();
 const accepted=entry();check(accepted?.state==='accepted'&&accepted.body.expected_version===1,'HTTP normal 202 accepted saved version');check($('raw-result').textContent.includes('source_goal_card')&&!$('raw-result').textContent.includes('UNSAVED MUST NOT EXECUTE'),'HTTP actual Run frozen source excludes unsaved edit');
 const worker=await fetch(info.base+'/test-only-goal-worker',{method:'POST'});assert(worker.ok);await w.showRun(accepted.runId);check($('result').textContent.includes('PARTIAL')&&$('result').textContent.includes('MOCK'),'HTTP normal Mock Worker leaves PARTIAL');check($('result').textContent.includes('合计')&&$('raw-result').textContent.includes('NOT_RUN'),'HTTP actual tool receipts and NOT_RUN displayed');
 const id=accepted.runId;await page();await w.refresh();check($('runs').querySelector('button'),'HTTP cold task history locates persisted run');await $('runs').querySelector('button').onclick();check(w.eval('activeRun')===id&&$('result').textContent.includes('PARTIAL'),'HTTP cold history read no new submission');
 fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({status:'PASS',checks,api:'ACTUAL_LOOPBACK_HTTP',worker:'NORMAL_MOCK',native:'NOT_RUN',loaded_source_sha256:loaded},null,2));
}
(async()=>{try{
 if(process.argv[3]==='HTTP'){await actualHttp();return;}
 await setup();check(!$('goal-card-run').disabled&&$('goal-card-run').textContent.includes('v1'),'saved card exposes saved version execution');$('goal-card-goal').value='UNSAVED';await w.executeGoalCard();check(JSON.stringify(posts()[0].body)===JSON.stringify({expected_version:1,expected_fingerprint:fp,request_key:posts()[0].body.request_key}),'closed body binds saved version/fingerprint excludes unsaved fields');check(entry().state==='accepted'&&$('result').textContent.includes('PARTIAL')&&$('result').textContent.includes('MOCK'),'actual read renders PARTIAL Mock receipts');check($('goal-card-run-status').textContent.includes('NOT_RUN')&&$('goal-card-run-status').textContent.includes('未生成候选'),'execution never claims goal acceptance or candidate');
 for(const mode of ['lost','bad']){await setup();postMode=mode;await w.executeGoalCard();const original=JSON.stringify(posts()[0].body);check(entry().state==='unknown'&&!$('goal-card-run-recover').hidden,'lost/malformed receipt UNKNOWN '+mode);await w.executeGoalCard();check(posts().length===1,'UNKNOWN no duplicate ordinary click '+mode);postMode='422';await w.executeGoalCard(true);check(entry().state==='unknown'&&JSON.stringify(posts()[1].body)===original,'later 422 keeps original UNKNOWN body/key '+mode);postMode='ok';await w.executeGoalCard(true);check(entry().state==='accepted'&&JSON.stringify(posts()[2].body)===original,'explicit same-key recovery accepts original '+mode);}
 await setup();postMode='422';await w.executeGoalCard();check(entry().state==='rejected'&&$('goal-card-run-recover').hidden,'first definite 422 rejected not unknown');
 for(const mode of ['error','wrong','wrongSnapshot']){await setup();readMode=mode;await w.executeGoalCard();check(entry().state==='accepted-read-error'&&!$('raw-result').textContent,'read failure/source mismatch clears protected result '+mode);const count=posts().length;readMode='ok';await w.executeGoalCard(true);check(posts().length===count&&entry().state==='accepted','accepted recovery only GET '+mode);}
 for(const kind of ['project','identity','card']){await setup();hold={url:`/api/projects/${pid}/goal-cards/${cid}/runs`,used:false};const pending=w.executeGoalCard();while(!hold.used)await settle();const old=hold;
 if(kind==='project'){$('project-select').value=other;w.clearGoalCard();$('project-select').value=pid;w.clearGoalCard();}else if(kind==='identity'){w.clearIdentityView();w.eval('token="synthetic-B"');w.clearIdentityView();w.eval('token="synthetic-A"');$('project-select').append(new w.Option('A',pid));$('project-select').value=pid;}else w.clearGoalCard();await w.showGoalCard(cid);old.resolve(receipt);await pending;check(!calls.some(c=>c.url===`/api/runs/${rid}`)&&!$('raw-result').textContent,kind+' ABA late POST cannot select/read old run');}
 await setup();hold={url:`/api/runs/${rid}`,used:false};const pending=w.executeGoalCard();while(!hold.used)await settle();const old=hold;w.clearGoalCard();await w.showGoalCard(cid);old.resolve(run);await pending;check(!$('raw-result').textContent&&!$('result').textContent.includes('ACTUAL SYNTHETIC RESULT'),'late run read cannot repaint new card');
 await setup();w.clearGoalCard();await w.executeGoalCard();check(posts().length===0&&$('goal-card-run').disabled,'unsaved card cannot execute');
 const result={status:'PASS',checks,api:'CONTROLLED_NOT_HTTP',native:'NOT_RUN',source_sha256:crypto.createHash('sha256').update(fs.readFileSync(path.join(web,'app.js'))).digest('hex')};fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
 }catch(e){fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({status:'FAIL',checks,error:e.message},null,2));console.error(e.stack);process.exitCode=1;}finally{dom?.window.close();}})();
