'use strict';
// Real app.js/full DOM, owned real HTTP fixture and 2500ms timer; no latch mirror.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),http=require('node:http'),{JSDOM}=require('jsdom');
const {installOwnedPageLifecycle}=require('./natural_goal_ui.cjs'),out=process.argv[2],kind=process.argv[3],web=path.join(__dirname,'../src/sim2act/web');let dom,server,pending,received,errors=[];
const wait=async test=>{const end=Date.now()+10000;while(Date.now()<end){if(test())return;await new Promise(r=>setTimeout(r,10));}throw Error('Expected actual request');};
(async()=>{try{server=http.createServer((request,response)=>{if(request.method==='POST'){response.end(JSON.stringify({run_id:'run_'+'4'.repeat(32)}));return;}received=true;if(kind==='network-error'){response.destroy();return;}response.writeHead(200,{'Content-Type':'application/json'});response.write('{"mode":');pending=()=>response.end('"MOCK","api":"up","worker":"up"}');});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base='http://127.0.0.1:'+server.address().port;
 dom=new JSDOM(fs.readFileSync(path.join(web,'index.html'),'utf8'),{url:base,runScripts:'dangerously'});const w=dom.window;w.crypto.randomUUID=require('node:crypto').randomUUID;w.fetch=async(url,opts)=>{const response=await fetch(new URL(url,base),opts);if(kind==='controlled-lost'&&opts?.method==='POST'){await response.arrayBuffer();const e=Error('Expected acceptance transport loss');e.controlledAcceptanceLoss=true;throw e;}return response;};const lifecycle=installOwnedPageLifecycle(w);const script=w.document.createElement('script');script.textContent=fs.readFileSync(path.join(web,'app.js'),'utf8');w.document.body.append(script);
 if(kind==='controlled-lost'){w.document.querySelector('#project-select').append(new w.Option('P','proj_'+'1'.repeat(32)));w.document.querySelector('#goal').value='original';w.eval('token="synthetic-A"');await w.document.querySelector('#run-form').onsubmit({preventDefault(){}});assert.equal(w.eval('runSubmissionEntry().state'),'unknown');const state=await lifecycle.drain();assert.equal(state.errors,0);fs.writeFileSync(path.join(out,'result.json'),JSON.stringify({status:'PASS',case:kind,state,api:'OWNED_LOOPBACK_HTTP'}));return;}
 if(kind==='action-error'){const button=w.document.createElement('button');w.document.body.append(button);button.onclick=async()=>{await w.api('/health');throw Error('OWNED_ASYNC_UNKNOWN');};button.click();}
 await wait(()=>received);if(kind==='network-error'){await wait(()=>lifecycle.snapshot().errors>0);await assert.rejects(lifecycle.drain());assert(lifecycle.snapshot().errors>0);}
 else{let done=false;const drain=lifecycle.drain().then(value=>{done=true;return value;},error=>{done=true;throw error;});await new Promise(r=>setTimeout(r,50));assert.equal(done,false,'actual body/UI chain pending must not drain early');assert(lifecycle.snapshot().requests>0);assert.equal(lifecycle.snapshot().intervals,0);pending();if(kind==='action-error'){await assert.rejects(drain,/OWNED_ASYNC_UNKNOWN/);}else{const state=await drain;assert.equal(state.background_in_flight,false);assert.equal(state.requests,0);assert.equal(state.actions,0);assert(w.document.querySelector('#health').textContent.includes('MOCK'));}}
 fs.writeFileSync(path.join(out,'result.json'),JSON.stringify({status:'PASS',case:kind,state:lifecycle.snapshot(),api:'OWNED_LOOPBACK_HTTP',timer:'ACTUAL_2500MS'}));
 }catch(error){errors.push(error.message);console.error(error.stack);process.exitCode=1;}finally{dom?.window.close();if(server){server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}if(errors.length)fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({status:'FAIL',errors}));}})();
