'use strict';
// Shared actual-HTTP oracle. JSDOM is not native evidence; --playwright requires sandbox.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
function installOwnedPageLifecycle(window){
 const intervals=new Set(),actions=new Set(),errors=[];let requests=0;
 const note=error=>{if(!errors.includes(error))errors.push(error);};
 const track=result=>{if(result&&typeof result.then==='function'){const action=Promise.resolve(result);actions.add(action);action.then(()=>actions.delete(action),error=>{note(error);actions.delete(action);});}return result;};
 const set=window.setInterval.bind(window),clear=window.clearInterval.bind(window);
 window.setInterval=(callback,delay,...args)=>{const id=set((...values)=>{try{return track(callback(...values));}catch(error){note(error);throw error;}},delay,...args);intervals.add(id);return id;};
 window.clearInterval=id=>{intervals.delete(id);clear(id);};
 const fetch=window.fetch;
 window.fetch=async(...args)=>{requests++;try{const response=await fetch(...args);const json=response.json.bind(response);response.json=async()=>{requests++;try{return await json();}catch(error){note(error);throw error;}finally{requests--;}};return response;}catch(error){if(!error.controlledAcceptanceLoss)note(error);throw error;}finally{requests--;}};
 for(const name of ['onclick','onchange','onsubmit']){const descriptor=Object.getOwnPropertyDescriptor(window.HTMLElement.prototype,name);assert(descriptor?.set,'Actual DOM handler descriptor');Object.defineProperty(window.HTMLElement.prototype,name,{...descriptor,set(fn){descriptor.set.call(this,typeof fn==='function'?function(...args){try{return track(fn.apply(this,args));}catch(error){note(error);throw error;}}:fn);}});}
 window.addEventListener('error',event=>note(event.error||Error(event.message)));
 window.addEventListener('unhandledrejection',event=>note(event.reason||Error('Unhandled page rejection')));
 const snapshot=()=>({requests,actions:actions.size,errors:errors.length,intervals:intervals.size,background_in_flight:window.eval('typeof backgroundRefreshInFlight!=="undefined" && backgroundRefreshInFlight')});
 return {snapshot,async drain(){for(const id of intervals)clear(id);intervals.clear();const deadline=Date.now()+10000;while(Date.now()<deadline){const observed=snapshot();if(observed.requests===0&&observed.actions===0&&!observed.background_in_flight){await new Promise(resolve=>setImmediate(resolve));const final=snapshot();if(final.requests===0&&final.actions===0&&!final.background_in_flight){if(errors.length)throw errors[0];return final;}}await new Promise(resolve=>setTimeout(resolve,10));}throw Error('Timeout: owned page drain');}};
}
module.exports={installOwnedPageLifecycle};
if(require.main===module){
const out=process.argv[2],info=JSON.parse(fs.readFileSync(path.join(out,'info.json'),'utf8')),native=process.argv.includes('--playwright'),checks=[],requests=[],loaded={};let dom,browser,page,adapter,fault=null,hold=null,lifecycle=null;const pageLifecycle=[];
const wait=async(fn,label)=>{const until=Date.now()+10000;while(Date.now()<until){if(await fn())return;await new Promise(r=>setTimeout(r,10));}throw Error('Timeout: '+label);};
const check=(condition,label)=>{assert(condition,label);checks.push(label);};
const origin=new URL(info.base).origin;
const canonical=value=>JSON.stringify(value,(key,item)=>item&&typeof item==='object'&&!Array.isArray(item)?Object.fromEntries(Object.keys(item).sort().map(k=>[k,item[k]])):item);
function alter(data,mode){if(mode==='alter-plan')data.natural_plan.plan.interpretation.objective='COHERENT_TAMPER_WITH_ORIGINAL_FP';else if(mode==='alter-fp')data.natural_plan.fingerprint='b'.repeat(64);else if(mode==='validation-failed')data.natural_plan.validation='FAILED';else if(mode==='version-bool')data.version=true;else if(mode==='policy-false')data.natural_plan.confirmation_required=false;else if(mode==='alter-confirm'){data.goal_acceptance='PASS';data.candidate_generated=true;}else{data.natural_plan.plan.version='unknown-schema.v9';data.natural_plan.fingerprint=crypto.createHash('sha256').update(canonical(data.natural_plan.plan)).digest('hex');}}
async function wire(url,opts={}){const target=new URL(url,info.base);assert.equal(target.origin,origin,'No external browser request');const record={path:target.pathname,method:opts.method||'GET',body:opts.body&&JSON.parse(opts.body)};requests.push(record);const result=await fetch(target,opts);if(hold&&!hold.used&&target.pathname===hold.path&&record.method===(hold.method||'GET')){hold.used=true;await new Promise(resolve=>{hold.release=resolve;});}
 if(fault&&record.path.endsWith(fault.suffix)&&record.method===fault.method){const mode=fault.mode;fault=null;if(mode==='lost'){await result.arrayBuffer();const loss=Error('controlled lost actual acceptance');loss.controlledAcceptanceLoss=true;throw loss;}if(['alter-plan','alter-schema','alter-fp','validation-failed','version-bool','policy-false','alter-confirm'].includes(mode)){const data=await result.json();alter(data,mode);return new Response(JSON.stringify(data),{status:result.status,headers:{'Content-Type':'application/json'}});}}
 return result;
}
async function closeDom(){if(!dom)return;try{pageLifecycle.push(await lifecycle.drain());}finally{dom.window.close();dom=null;lifecycle=null;}}
async function fresh(){await closeDom();if(page)await page.close();
 if(native){page=await browser.newPage();await page.route('**/*',async route=>{const req=route.request(),target=new URL(req.url());assert.equal(target.origin,origin);requests.push({path:target.pathname,method:req.method(),body:req.postData()&&JSON.parse(req.postData())});if(hold&&!hold.used&&target.pathname===hold.path&&req.method()===(hold.method||'GET')){const response=await route.fetch();hold.used=true;await new Promise(resolve=>{hold.release=resolve;});await route.fulfill({response});return;}if(fault&&target.pathname.endsWith(fault.suffix)&&req.method()===fault.method){const mode=fault.mode;fault=null;const response=await route.fetch();if(mode==='lost'){await route.abort('failed');return;}if(['alter-plan','alter-schema','alter-fp','validation-failed','version-bool','policy-false','alter-confirm'].includes(mode)){const data=await response.json();alter(data,mode);await route.fulfill({response,json:data});return;}}await route.continue();});page.on('response',async response=>{if(response.url().endsWith('.js')){const code=await response.body();loaded[new URL(response.url()).pathname.slice(1)]=crypto.createHash('sha256').update(code).digest('hex');}});await page.goto(info.base);adapter={select:(id,v)=>page.locator('#'+id).selectOption(v),fill:(id,v)=>page.locator('#'+id).fill(v),click:id=>page.locator('#'+id).click(),text:id=>page.locator('#'+id).textContent(),disabled:id=>page.locator('#'+id).isDisabled(),checked:(id,v)=>page.locator('#'+id).setChecked(v),eval:fn=>page.evaluate(fn)};
 }else{const {JSDOM}=require('jsdom');dom=new JSDOM(await(await fetch(info.base)).text(),{url:info.base,runScripts:'dangerously'});const w=dom.window;w.crypto.randomUUID=()=>crypto.randomUUID();Object.defineProperty(w.crypto,'subtle',{value:crypto.webcrypto.subtle});w.TextEncoder=require('node:util').TextEncoder;w.fetch=wire;lifecycle=installOwnedPageLifecycle(w);
 for(const name of [...w.document.querySelectorAll('script[src]')].map(s=>new URL(s.src).pathname.slice(1))){const code=await(await fetch(info.base+'/'+name)).text();loaded[name]=crypto.createHash('sha256').update(code).digest('hex');const s=w.document.createElement('script');s.textContent=code;w.document.body.append(s);}
 const get=id=>{const el=w.document.getElementById(id);assert(el,'Actual DOM id '+id);return el;};adapter={select:async(id,v)=>{get(id).value=v;await get(id).onchange?.({preventDefault(){}});},fill:async(id,v)=>{get(id).value=v;},click:async id=>{const el=get(id);assert(!el.disabled,'Enabled '+id);await el.onclick?.({preventDefault(){}});},text:async id=>get(id).textContent,disabled:async id=>get(id).disabled,checked:async(id,v)=>{get(id).checked=v;await get(id).onchange?.({preventDefault(){}});},eval:async fn=>w.eval('('+fn.toString()+')()')};}
 await adapter.fill('token','synthetic-test-A');await adapter.click('connect');await wait(()=>adapter.eval(()=>!!document.querySelector('#goal-card-list button')),'actual goal history');
 if(native)await page.locator('#goal-card-list button').first().click();else await dom.window.document.querySelector('#goal-card-list button').onclick({preventDefault(){}});
 await wait(()=>adapter.eval(()=>!!activeGoalCard),'opened saved card');
}
const state=()=>fetch(info.base+'/test-only-nl-state').then(r=>r.json());const worker=()=>fetch(info.base+'/test-only-nl-worker',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}).then(r=>{assert(r.ok,'Actual fixture worker accepted');return r.json();});
(async()=>{let result;try{
 if(native){const {chromium}=require('playwright');browser=await chromium.launch({executablePath:'/usr/bin/chromium',chromiumSandbox:true,headless:true,timeout:10000});}
 await fresh();check((await adapter.text('natural-goal-config')).includes(info.case==='disabled'?'默认关闭':'授权为 0'),'current project provider status rendered');check((await state()).wires===0,'opening status does not send model');
 if(info.case==='valid'){
 await adapter.fill('goal-card-title','OLD_EDIT_TITLE');await adapter.fill('goal-card-goal','OLD_EDIT_GOAL');hold={path:`/api/projects/${info.project}/natural-planning-status`,used:false};const opening=native?page.locator('#goal-card-list button').first().click():dom.window.document.querySelector('#goal-card-list button').onclick({preventDefault(){}});await wait(()=>hold.used,'actual configuration GET held');check(await adapter.eval(()=>document.querySelector('#goal-card-title').value)==info.saved_title&&await adapter.eval(()=>document.querySelector('#goal-card-goal').value)==info.saved_goal,'configuration pending shows actual saved fields, never old edits bound to new card');const statusHeld=hold;await adapter.select('project-select',info.other_project);await adapter.select('project-select',info.project);const freshConfig=await adapter.text('natural-goal-config');hold=null;statusHeld.release();await opening;check(await adapter.text('natural-goal-config')===freshConfig,'late project ABA configuration cannot paint');if(native)await page.locator('#goal-card-list button').first().click();else await dom.window.document.querySelector('#goal-card-list button').onclick({preventDefault(){}});
 }
 await adapter.fill('goal-card-goal','UNSAVED TEXT MUST NOT ENTER SOURCE');if(info.case==='valid'){fault={suffix:'/planned-runs',method:'POST',mode:'lost'};hold={path:`/api/projects/${info.project}/goal-cards/${info.card}/planned-runs`,method:'POST',used:false};const sending=adapter.click('natural-goal-generate');await wait(()=>hold.used,'held real planned acceptance');check(await adapter.disabled('natural-goal-generate'),'inflight generate disabled');await adapter.eval(()=>document.querySelector('#natural-goal-generate').click());check(requests.filter(r=>r.path.endsWith('/planned-runs')).length===1,'held planned double ordinary click sends one POST');const old=hold;await adapter.select('project-select',info.other_project);await adapter.select('project-select',info.project);const beforeGet=requests.filter(r=>r.path.startsWith('/api/runs/')).length;hold=null;old.release();await sending;check(requests.filter(r=>r.path.startsWith('/api/runs/')).length===beforeGet&&!(await adapter.text('raw-result')),'project ABA late planned acceptance no old GET or repaint');if(native)await page.locator('#goal-card-list button').first().click();else await dom.window.document.querySelector('#goal-card-list button').onclick({preventDefault(){}});}else await adapter.click('natural-goal-generate');if(info.case==='valid'){await wait(()=>adapter.eval(()=>!document.querySelector('#natural-goal-recover').hidden),'explicit UNKNOWN recovery');check((await adapter.text('natural-goal-status')).includes('UNKNOWN'),'actual lost acceptance UNKNOWN');await adapter.click('natural-goal-recover');const retries=requests.filter(r=>r.path.endsWith('/planned-runs'));check(retries.length===2&&JSON.stringify(retries[0].body)===JSON.stringify(retries[1].body),'lost acceptance same original body/key recovery');}await wait(async()=>{const s=await state();return s.runs.length===1;},'actual planned Run');let s=await state();const rid=s.runs[0].id;
 const post=requests.find(r=>r.method==='POST'&&r.path.endsWith('/planned-runs'));check(post&&post.body.expected_version===info.version&&post.body.expected_fingerprint===info.fingerprint&&Object.keys(post.body).sort().join(',')==='expected_fingerprint,expected_version,request_key','closed saved version body excludes unsaved edits');check(s.operations===0&&s.wires===0,'acceptance does not execute plan or send model');
 await worker();await adapter.click('natural-goal-read');s=await state();
 if(['disabled','invalid_schema'].includes(info.case)){check(s.operations===0,'disabled/invalid plan executes zero Operations');check(s.runs[0].status===(info.case==='disabled'?'WAITING_RESOURCE':'FAILED'),'actual disabled or schema failure state');check(s.wires===(info.case==='disabled'?0:1),'actual disabled zero send or one invalid offline provider receipt');check(!(await adapter.eval(()=>!!document.querySelector('#natural-goal-confirm')&&!document.querySelector('#natural-goal-confirm').disabled)),'no confirm enabled for absent/invalid plan');}
 else{
 check(s.runs[0].status==='WAITING_APPROVAL'&&s.operations===0&&s.wires===1,'valid offline plan waits approval with zero Operations');
 if(info.case==='cancel'){await adapter.click('natural-goal-cancel');s=await state();check(s.runs[0].status==='CANCELLED'&&s.operations===0,'explicit cancellation remains CANCELLED zero Operations');check(!(await adapter.eval(()=>document.querySelector('#natural-goal-confirm'))),'cancelled task has no confirm controls');result={status:'PASS',checks,api:'ACTUAL_LOOPBACK_HTTP',browser:native?'PROTECTED_PLAYWRIGHT':'JSDOM_NOT_NATIVE',loaded_source_sha256:loaded,case:info.case};return;}
 if(info.case==='revoke'){const revoked=await fetch(info.base+'/test-only-nl-revoke',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});assert(revoked.ok);await adapter.click('natural-goal-read');check(!(await adapter.eval(()=>document.querySelector('#natural-goal-plan')))&&!(await adapter.text('raw-result')),'actual resource revoke clears protected plan and source');check(!(await adapter.eval(()=>document.querySelector('#natural-goal-confirm'))),'revoked task has no confirm controls');check((await state()).operations===0,'revoke creates zero Operations');result={status:'PASS',checks,api:'ACTUAL_LOOPBACK_HTTP',browser:native?'PROTECTED_PLAYWRIGHT':'JSDOM_NOT_NATIVE',loaded_source_sha256:loaded,case:info.case};return;}
 hold={path:'/api/runs/'+rid,used:false};const lateRead=adapter.click('natural-goal-read');await wait(()=>hold.used,'held plan read before back');const oldRead=hold;await adapter.click('natural-goal-back');hold=null;oldRead.release();await lateRead;check(!(await adapter.eval(()=>document.querySelector('#natural-goal-plan')))&&!(await adapter.text('raw-result')),'back during held actual GET prevents late plan repaint');await adapter.click('natural-goal-read');check((await adapter.text('natural-goal-plan')).includes('<script>window.NL_XSS=1</script>'),'untrusted interpretation rendered literal');check(!(await adapter.eval(()=>window.NL_XSS)),'no script execution');check(await adapter.disabled('natural-goal-confirm'),'unchecked ack blocks confirmation');await adapter.checked('natural-goal-ack',true);fault={suffix:'/api/runs/'+rid,method:'GET',mode:'alter-plan'};await adapter.click('natural-goal-read');check(!(await adapter.eval(()=>!!document.querySelector('#natural-goal-confirm')&&!document.querySelector('#natural-goal-confirm').disabled))&&!(await adapter.text('natural-goal-plan')).includes('COHERENT_TAMPER_WITH_ORIGINAL_FP'),'coherently altered plan with original hash rejected before confirmation');await adapter.click('natural-goal-read');check(await adapter.disabled('natural-goal-confirm'),'fresh valid read resets ack');for(const mode of ['alter-schema','alter-fp','validation-failed','version-bool','policy-false']){await adapter.checked('natural-goal-ack',true);fault={suffix:'/api/runs/'+rid,method:'GET',mode};await adapter.click('natural-goal-read');check(!(await adapter.eval(()=>!!document.querySelector('#natural-goal-confirm'))),mode+' actual response projection closes controls');await adapter.click('natural-goal-read');check(!(await adapter.eval(()=>document.querySelector('#natural-goal-ack').checked)),mode+' error followed by valid read requires fresh unchecked ack');}
 const before=requests.filter(r=>r.method==='POST').length;await adapter.checked('natural-goal-ack',true);check(!(await adapter.disabled('natural-goal-confirm')),'explicit ack enables current exact plan confirmation');fault={suffix:'/confirm-natural-plan',method:'POST',mode:'alter-confirm'};hold={path:'/api/runs/'+rid,used:false};const confirming=adapter.click('natural-goal-confirm');await wait(()=>hold.used,'followup actual confirmed Run held');check(await adapter.eval(()=>[...naturalGoalConfirmations.values()].some(entry=>entry.state==='unknown')),'malformed confirmation 200 metadata stays UNKNOWN until authoritative read');const acceptedState=await state();check(acceptedState.runs[0].status==='QUEUED'&&acceptedState.operations===0,'malformed wire still has real server confirmation and no executed tools');const heldConfirmed=hold;hold=null;heldConfirmed.release();await confirming;check(await adapter.eval(()=>[...naturalGoalConfirmations.values()].some(entry=>entry.state==='accepted')),'actual GET confirmed receipt resolves UNKNOWN without false server confirmation');s=await state();check(s.runs[0].status==='QUEUED'&&s.operations===0,'confirmation only queues exact plan');const confirmation=requests.find(r=>r.path.endsWith('/confirm-natural-plan'));check(confirmation?.body.expected_version>0&&/^[a-f0-9]{64}$/.test(confirmation.body.expected_plan_fingerprint)&&Object.keys(confirmation.body).sort().join(',')==='expected_plan_fingerprint,expected_version,request_key','closed confirmation version fingerprint key');check(requests.filter(r=>r.method==='POST').length===before+1,'one explicit confirmation POST');await worker();await adapter.click('natural-goal-read');s=await state();check(s.runs[0].status==='PARTIAL'&&s.operations===1&&s.wires===1,'normal Worker actual receipt without second planner call');check((await adapter.text('result')).includes('19')&&(await adapter.text('result')).includes('NOT_RUN'),'actual sum and nonaccepted goal semantics');
 const count=requests.filter(r=>r.method==='POST').length;await fresh();if(native)await page.locator('#runs button').first().click();else await dom.window.document.querySelector('#runs button').onclick({preventDefault(){}});check(requests.filter(r=>r.method==='POST').length===count,'cold page/history issues zero automatic POST');check((await adapter.text('result')).includes('PARTIAL'),'cold actual history retains technical result');const denied=await fetch(info.base+'/api/runs/'+rid,{headers:{Authorization:'Bearer synthetic-test-B'}});check(denied.status===403,'actual cross-owner Run denied');
 hold={path:'/api/runs/'+rid,used:false};const reading=native?page.locator('#runs button').first().click():dom.window.document.querySelector('#runs button').onclick({preventDefault(){}});await wait(()=>hold.used,'actual old Run read held');const held=hold;await adapter.fill('token','synthetic-test-B');await adapter.click('connect');await adapter.fill('token','synthetic-test-A');await adapter.click('connect');hold=null;held.release();await reading;await new Promise(r=>setTimeout(r,20));check(!(await adapter.text('raw-result')),'identity ABA held actual Run cannot redraw protected source/result');check(requests.filter(r=>r.method==='POST').length===count,'cold/identity ABA never auto submits or confirms');
 }
 result={status:'PASS',checks,api:'ACTUAL_LOOPBACK_HTTP',browser:native?'PROTECTED_PLAYWRIGHT':'JSDOM_NOT_NATIVE',loaded_source_sha256:loaded,case:info.case};
 }catch(error){fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({status:'FAIL',checks,error:error.message,browser:native?'PROTECTED_PLAYWRIGHT':'JSDOM_NOT_NATIVE'},null,2));console.error(error.stack);process.exitCode=1;}
 finally{if(hold?.release){hold.release();hold=null;}try{await closeDom();if(page)await page.close();if(browser)await browser.close();}catch(error){result=null;process.exitCode=1;fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({status:'FAIL',checks,error:error.message,phase:'PAGE_CLEANUP',page_lifecycle:pageLifecycle},null,2));console.error(error.stack);}if(result){result.page_lifecycle=pageLifecycle;fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));}}
})();

}
