'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),vm=require('node:vm'),crypto=require('node:crypto'),{JSDOM}=require('jsdom');
const root=process.argv[2],info=JSON.parse(fs.readFileSync(path.join(root,'info.json'))),checks=[],requests=[],loaded={};let dom,w,drop=false,holdList=false,releaseList=null;
const check=(ok,name)=>{assert.ok(ok,name);checks.push(name);};
const wait=async fn=>{const until=Date.now()+10000;while(!await fn()){assert.ok(Date.now()<until,'page wait timeout');await new Promise(r=>setTimeout(r,10));}};
const $=id=>w.document.getElementById(id);
async function click(id){await $(id).onclick({preventDefault(){}});}
async function load(){dom?.window.close();dom=new JSDOM(await(await fetch(info.base)).text(),{url:info.base,runScripts:'outside-only'});w=dom.window;w.setInterval=()=>0;w.structuredClone=structuredClone;w.TextEncoder=TextEncoder;Object.defineProperty(w.crypto,'subtle',{value:crypto.webcrypto.subtle});w.crypto.randomUUID=crypto.randomUUID;
 w.fetch=async(url,options={})=>{const u=new URL(url,info.base);assert.equal(u.origin,info.base,'local page only');const record={path:u.pathname,method:options.method||'GET',body:options.body&&JSON.parse(options.body)};requests.push(record);const r=await fetch(u,options);if(holdList&&record.method==='GET'&&record.path===`/api/projects/${info.project}/natural-activations`){holdList=false;await new Promise(resolve=>releaseList=resolve);}if(drop&&record.method==='POST'&&record.path.endsWith('/planned-runs')){drop=false;assert.equal(r.status,202);await r.clone().json();throw Error('Owned test delivery loss after accepted Run');}return r;};
 for(const tag of w.document.querySelectorAll('script[src]')){const name=tag.getAttribute('src');const text=await(await fetch(info.base+name)).text();loaded[name]=crypto.createHash('sha256').update(text).digest('hex');vm.runInContext(text,dom.getInternalVMContext());}
 $('token').value='synthetic-test-A';await click('connect');await wait(()=>$('project-select').value===info.project&&$('login').hidden);}
const worker=()=>fetch(info.base+'/test-only-activation-worker',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}).then(r=>assert.equal(r.status,200));
const control=action=>fetch(info.base+'/test-only-activation-control/'+action,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}).then(r=>assert.equal(r.status,200));
const posts=()=>requests.filter(r=>r.method==='POST').length;
async function selectSession(){await click('natural-activation-refresh');$('natural-activation-select').value=info.session;$('natural-activation-select').onchange();check($('natural-activation-status').textContent.includes('离线测试会话')&&$('natural-activation-status').textContent.includes('0/2')&&$('natural-activation-status').textContent.includes('RPM1'),'approved exact offline scope, budget and rate visible');}
async function openGoal(kind){const line=[...$('natural-activation-goals').children].find(n=>n.textContent.includes(kind==='read_preview'?'合成CSV预览':'合成quantity_z'));assert.ok(line);await line.querySelector('button').onclick({preventDefault(){}});check(w.eval('activeGoalCard.id')===info.cards[kind],'only bound exact saved goal opened');}
(async()=>{try{
 await load();await selectSession();await openGoal('read_preview');$('goal-card-goal').value='UNSAVED CUSTOM MUST NOT LEAVE';drop=true;await click('natural-goal-generate');check($('natural-goal-status').textContent.includes('UNKNOWN'),'unknown accepted intent retained');await click('natural-goal-recover');const sends=requests.filter(r=>r.path.endsWith('/planned-runs'));check(sends.length===2&&JSON.stringify(sends[0])===JSON.stringify(sends[1])&&sends[0].path.startsWith('/api/natural-activations/'+info.session+'/'),'same frozen activation endpoint and body recovery, no unbound fallback');
 check($('natural-goal-plan').textContent.includes('120 秒')&&$('natural-goal-plan').textContent.includes('不是本计划的执行确认'),'acceptance deadline and distinct session authority visible before planning');
 await worker();await click('natural-goal-read');check($('natural-goal-confirm').disabled&&$('natural-goal-plan').textContent.includes('工具操作为 0'),'valid offline plan still requires explicit execution acknowledgement');
 if(info.case!=='valid'){
   await control(info.case==='expired'?'expire-run':'revoke');await click('natural-goal-read');const before=posts();check($('natural-goal-confirm').disabled&&$('natural-goal-ack').disabled,'expired task or revoked session cannot confirm');check($('natural-goal-plan').textContent.includes(info.case==='expired'?'期限已过':'会话不可执行'),'specific blocked deadline/session reason visible');await click('natural-goal-confirm');check(posts()===before,'blocked UI confirmation creates zero POST');
 }else{
   const confirm=async()=>{$('natural-goal-ack').checked=true;$('natural-goal-ack').onchange();check(!$('natural-goal-confirm').disabled,'separate explicit plan acknowledgement enables confirmation');await click('natural-goal-confirm');await worker();await click('natural-goal-read');};
   await confirm();check($('raw-result').textContent.includes('PARTIAL')&&$('raw-result').textContent.includes('candidate_generated')&&$('raw-result').textContent.includes('NOT_RUN'),'terminal result not promoted to application or semantic acceptance');
   await control('next-minute');await click('natural-activation-refresh');
   const custom=await w.api(`/api/projects/${info.project}/goal-cards`,'POST',{title:'custom outside activation',goal:'custom outside activation',known:[],assumptions:[],unresolved:[],constraints:[],acceptance_checks:[],resource_refs:[]});await w.showGoalCard(custom.id);const customBefore=posts();check($('natural-goal-generate').disabled,'custom saved goal cannot use fixed synthetic activation');await w.generateNaturalGoal();check(posts()===customBefore,'direct UI action does not fall back to unbound custom route');
   await openGoal('sum_quantity_z');await click('natural-goal-generate');await worker();await click('natural-goal-read');await confirm();check($('raw-result').textContent.includes('"sum": "19"'),'second fixed goal gets actual tool sum19');
   const rid=w.eval('activeRun'),before=posts();await load();await w.showRun(rid);check($('raw-result').textContent.includes('"sum": "19"')&&posts()===before,'cold page historical read creates no task/approval POST');await click('natural-activation-refresh');$('natural-activation-select').value=info.session;$('natural-activation-select').onchange();check($('natural-activation-status').textContent.includes('2/2')&&$('natural-activation-status').textContent.includes('预算已用尽'),'used budget visible after cold read');await openGoal('sum_quantity_z');check($('natural-goal-generate').disabled,'charged goal cannot start another UI intent');
   holdList=true;const pendingList=click('natural-activation-refresh');await wait(()=>releaseList);$('project-select').value=info.other;await $('project-select').onchange({preventDefault(){}});releaseList();await pendingList;check(w.eval('naturalActivationSelection===null')&&!$('natural-activation-goals').textContent,'project transition and delayed list clear exact selected session');
   $('token').value='synthetic-test-B';await click('connect');check(w.eval('naturalActivationSelection===null&&naturalActivationRows.length===0'),'identity change cannot restore prior scopes');
 }
 const result={status:'PASS',case:info.case,browser:'JSDOM_NOT_NATIVE',api:'ACTUAL_LOOPBACK_HTTP',checks,loaded_source_sha256:loaded,model_network:0};fs.writeFileSync(path.join(root,'results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
 }catch(error){console.error(error.stack);process.exitCode=1;}finally{dom?.window.close();}})();
