'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{JSDOM}=require('jsdom');
const root=process.argv[2],info=JSON.parse(fs.readFileSync(path.join(root,'info.json'))),checks=[],requests=[],hashes={};
let dom,w,$,mode='',release;
const check=(ok,label)=>{assert(ok,label);checks.push(label);};
const wait=async(fn,label)=>{const end=Date.now()+6000;while(Date.now()<end){if(fn())return;await new Promise(r=>setTimeout(r,10));}throw Error('Timeout '+label);};
async function setup(){
 dom?.window.close();const html=await(await fetch(info.base)).text();hashes['index.html']=crypto.createHash('sha256').update(html).digest('hex');dom=new JSDOM(html,{url:info.base,runScripts:'dangerously'});w=dom.window;$=id=>w.document.getElementById(id);
 w.fetch=async(url,opts={})=>{const target=new URL(url,info.base);assert.equal(target.origin,info.base);const entry={path:target.pathname,method:opts.method||'GET',body:opts.body&&JSON.parse(opts.body)};requests.push(entry);
 if(mode==='later-422'&&entry.method==='POST'&&entry.path.endsWith('/previews')){mode='';return {ok:false,status:422,json:async()=>({detail:[{msg:'controlled later 422 after unknown'}]})};}
 const response=await fetch(target,opts);
 if(mode==='bad-open'&&entry.path.startsWith('/api/apps/')){mode='';const bad=await response.json();bad.candidate.report_proof.source_run_id='run_'+'0'.repeat(32);return {ok:true,status:200,json:async()=>bad};}
 if(mode==='bad-history'&&entry.path.endsWith('/history')){mode='';const bad=await response.json();bad.fingerprint='0'.repeat(64);return {ok:true,status:200,json:async()=>bad};}
 if(mode==='coherent-history-source'&&entry.path.endsWith('/history')){mode='';const bad=await response.json();bad.candidate.report_proof.source_run_id='run_'+'0'.repeat(32);bad.candidate.manifest.source_run_ref=bad.candidate.report_proof.source_run_id;return {ok:true,status:200,json:async()=>bad};}
 if(mode==='bad-history-run'&&entry.path.endsWith('/history')){mode='';const bad=await response.json();bad.history[0].run.phase='source';return {ok:true,status:200,json:async()=>bad};}
 if(mode==='history-denied'&&entry.path.endsWith('/history')){mode='';return {ok:false,status:403,json:async()=>({error:{code:'PERMISSION_DENIED'}})};}

 if(mode.startsWith('promotion-')&&entry.path.endsWith('/manifest-preview')){const damage=mode.slice(10);mode='';const bad=await response.json(),proof=bad.candidate.report_proof;if(damage==='parent')proof.named_app_id='app_'+'0'.repeat(32);else if(damage==='parent-fingerprint')proof.expected_named_fingerprint='0'.repeat(64);else if(damage==='check')proof.expected_check_fingerprint='0'.repeat(64);else if(damage==='extract')proof.extraction_run_id='run_'+'0'.repeat(32);else if(damage==='target')proof.target_resource_id=info.source;else if(damage==='runtime')proof.runtime_id='runtime-other';else if(damage==='source'){proof.source_run_id='run_'+'0'.repeat(32);bad.candidate.manifest.source_run_ref=proof.source_run_id;}else if(damage==='limits')proof.limits.max_requests++;else throw Error('closed promotion fault');return {ok:true,status:201,json:async()=>bad};}
 if(mode==='lost-promote'&&entry.path.endsWith('/manifest-preview')){mode='';throw TypeError('Lost accepted promotion receipt');}
 if(mode==='bad-promote'&&entry.path.endsWith('/manifest-preview')){mode='';const bad=await response.json();delete bad.fingerprint;return {ok:true,json:async()=>bad};}
 if(mode==='lost-preview'&&entry.path.endsWith('/previews')&&entry.method==='POST'){mode='';throw TypeError('Lost accepted preview receipt');}
 if(mode==='bad-preview'&&entry.path.endsWith('/previews')&&entry.method==='POST'){mode='';const bad=await response.json();delete bad.phase;return {ok:true,json:async()=>bad};}
 if(mode==='hold-history'&&entry.path.endsWith('/history')){mode='';await new Promise(r=>release=r);release=null;}
 if(mode==='hold-open'&&entry.path.startsWith('/api/apps/')){mode='';await new Promise(r=>release=r);release=null;}
 if(mode==='hold-preview'&&entry.path.endsWith('/previews')&&entry.method==='POST'){mode='';await new Promise(r=>release=r);release=null;}
 return response;};
 for(const name of ['app.js','internal.js','protocol.js','use.js','conditional-runs.js','conditional-apps.js','report-manifest.js']){const code=await(await fetch(info.base+'/'+name)).text();hashes[name]=crypto.createHash('sha256').update(code).digest('hex');const s=w.document.createElement('script');s.textContent=code;w.document.body.append(s);}
 $('token').value='synthetic-test-A';$('connect').click();await wait(()=>$('project-select').value===info.project&&$('login').hidden,'identity/project');await w.refreshApps();
}
function facts(amount,receipt=true){for(const[k,v]of Object.entries({trip:'true',receipt:String(receipt),approved:'false',amount:String(amount),days:'2'}))$('manifest-report-'+k).value=v;}
const work=async phase=>{const r=await fetch(info.base+'/test-only-manifest-worker/'+phase,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});assert(r.ok,await r.text());};
(async()=>{try{
 await setup();await w.listConditionalSources();$('condition-resource').value=info.source;await w.openConditionalSource();for(const[k,v]of Object.entries({trip:'true',receipt:'true',approved:'false',amount:'680',days:'2'}))$('condition-run-source-'+k).value=v;await w.startBoundedSource();await work('source');await w.boundedAction(w.boundedRead);await w.extractBoundedCandidate();await work('extract');await w.boundedAction(w.boundedRead);check(!$('report-save-form').hidden,'same browser actual source finite-check and extraction enables named save');$('report-save-resource').value=info.fresh;$('report-save-name').value='Saved hypothetical travel report';await w.saveReportDraft();const namedList=await(await fetch(info.base+`/api/projects/${info.project}/conditional-apps`,{headers:{Authorization:'Bearer synthetic-test-A'}})).json();const named=namedList.items[0].id;check(namedList.items.length===1&&$('report-save-status').textContent.includes('PREVIEW_ONLY'),'same browser persists one named source wrapper without publication');await w.openReportApp(named);check(!$('report-manifest-promote').hidden,'named saved wrapper exposes explicit canonical promotion');mode='lost-promote';await w.promoteReportManifest();check(!$('report-manifest-promote-retry').hidden&&$('report-manifest-promote').disabled,'lost accepted promotion freezes intent');mode='bad-promote';await w.promoteReportManifest(true);check(!$('report-manifest-promote-retry').hidden,'malformed promotion preserves original intent');for(const damage of ['parent','parent-fingerprint','check','extract','target','runtime','source','limits']){mode='promotion-'+damage;await w.promoteReportManifest(true);check(!$('report-manifest-promote-retry').hidden&&$('report-manifest-promote').disabled,'real accepted promotion '+damage+' corruption retains original key and remains UNKNOWN');}await w.promoteReportManifest(true);
 const promotions=requests.filter(r=>r.path.endsWith('/manifest-preview'));check(promotions.length===11&&promotions.every(r=>JSON.stringify(r.body)===JSON.stringify(promotions[0].body)),'promotion retries exact body/key');check(promotions.every(r=>Object.keys(r.body).sort().join(',')==='expected_app_fingerprint,request_key'),'promotion caller supplies no program or authority');
 const coldOpenPosts=requests.filter(r=>r.method==='POST').length;
 const catalog=await(await fetch(info.base+'/api/apps',{headers:{Authorization:'Bearer synthetic-test-A'}})).json();const aid=w.eval('activeApp');check(catalog.items.some(a=>a.id===aid),'actual promotion ID belongs to generic catalog without summary schema assumptions');
 await setup();check($('app-list').textContent.includes('Saved hypothetical travel report')&&$('condition-run-plan').hidden,'fresh generic directory lists canonical persisted app without source context');check(requests.filter(r=>r.method==='POST').length===coldOpenPosts,'fresh generic page performs only reads and never auto-submits/provider');await w.showApp(aid);
 check(!$('manifest-report-form').hidden&&$('app-preview-form').hidden&&$('internal-panel').hidden&&$('csv-extraction-panel').hidden,'generic AppManifest opens dedicated typed Scenario without old lifecycle');check($('manifest-report-amount').value===''&&$('manifest-report-trip').value==='','new page does not prefill source facts');check($('app-manifest').textContent.includes('bounded_report')&&$('app-manifest').textContent.includes('workflow'),'real canonical manifest displayed');
 facts(500);$('manifest-report-amount').value='500.5';await w.runManifestReport();check(!$('manifest-report-submit').disabled&&$('manifest-report-retry').hidden&&$('app-output').textContent.includes('可修正'),'first actual HTTP422 rejects without accepted intent and clearly allows correction');
 facts(500);mode='lost-preview';await w.runManifestReport();check(!$('manifest-report-retry').hidden&&$('manifest-report-submit').disabled,'lost accepted preview locks inputs');mode='bad-preview';await w.runManifestReport(true);mode='later-422';await w.runManifestReport(true);check(!$('manifest-report-retry').hidden&&$('manifest-report-submit').disabled,'later 422 after unknown cannot release frozen intent');await w.runManifestReport(true);await work('allow');await w.readManifestHistory();
 facts(680,false);await w.runManifestReport();await work('block');await w.readManifestHistory();check($('app-history').textContent.includes('ALLOW')&&$('app-history').textContent.includes('BLOCK'),'two new Scenarios yield independent actual ALLOW/BLOCK Reports');
 for(const k of ['trip','receipt','approved','amount','days'])$('manifest-report-'+k).value='';await w.runManifestReport();await work('unknown');await w.readManifestHistory();check($('app-history').textContent.includes('UNKNOWN')&&$('app-origin').textContent.includes('PENDING')&&$('app-origin').textContent.includes('NOT_ACCEPTED'),'nullable new Scenario yields actual UNKNOWN while semantic and owner remain unaccepted');
 const previews=requests.filter(r=>r.path.endsWith('/previews')&&r.method==='POST');check(previews.filter(r=>r.body.input.amount===500).slice(0,4).every(r=>JSON.stringify(r.body)===JSON.stringify(previews.find(x=>x.body.input.amount===500).body)),'lost malformed later422 recovery preserves exact Scenario and key');check(previews.every(r=>Object.keys(r.body).sort().join(',')==='expected_candidate_fingerprint,input,request_key'),'cold caller supplies only typed input/version/key');check(previews.some(r=>r.body.input.trip_ended===null&&r.body.input.amount===null&&r.body.input.receipt_present===null&&r.body.input.approved===null&&r.body.input.elapsed_days===null)&&previews.some(r=>r.body.input.receipt_present===false&&Number.isInteger(r.body.input.amount)),'actual HTTP payload preserves null boolean/integer and explicit false');
 await setup();await w.showApp(aid);check($('app-history').textContent.includes('ALLOW')&&$('app-history').textContent.includes('BLOCK'),'second fresh page reloads actual distinct Run history');const history=await(await fetch(info.base+`/api/projects/${info.project}/apps/${aid}/history`,{headers:{Authorization:'Bearer synthetic-test-A'}})).json();check(history.history.length===3&&new Set(history.history.map(x=>x.run.run_id)).size===3,'three durable history records bind different actual Run IDs');
 mode='bad-history';await assert.rejects(w.readManifestHistory(),/VERSION_CONFLICT/);check($('app-history').textContent===''&&$('app-manifest').textContent===''&&$('manifest-report-form').hidden,'wrong history fingerprint clears old protected Report and manifest');await w.showApp(aid);mode='coherent-history-source';await assert.rejects(w.readManifestHistory(),/VERSION_CONFLICT/);check($('app-history').textContent===''&&$('app-manifest').textContent===''&&$('manifest-report-form').hidden,'coherent history source rewrite with unchanged fingerprint clears all old evidence');await w.showApp(aid);mode='bad-history-run';await assert.rejects(w.readManifestHistory(),/VERSION_CONFLICT/);check($('app-history').textContent===''&&$('manifest-report-form').hidden,'wrong history Run phase clears rather than rendering foreign source result');await w.showApp(aid);mode='history-denied';await assert.rejects(w.readManifestHistory(),/PERMISSION_DENIED/);check($('app-history').textContent===''&&$('app-output').textContent===''&&$('app-manifest').textContent==='','history permission failure clears all protected old evidence');await w.showApp(aid);
 mode='bad-open';await assert.rejects(w.showApp(aid),/VERSION_CONFLICT/);check($('app-history').textContent===''&&$('app-manifest').textContent===''&&$('manifest-report-form').hidden,'inspect source proof must match canonical manifest source reference');await w.showApp(aid);
 mode='hold-history';const projectABA=w.readManifestHistory();await wait(()=>release,'held project ABA history');const resumeProject=release;$('project-select').value=info.other;$('project-select').dispatchEvent(new w.Event('change'));await wait(()=>$('manifest-report-form').hidden,'project switch clears');$('project-select').value=info.project;$('project-select').dispatchEvent(new w.Event('change'));resumeProject();await projectABA;check($('app-history').textContent===''&&$('app-manifest').textContent===''&&$('manifest-report-form').hidden,'real project onchange ABA cannot restore late protected history');await w.showApp(aid);
 mode='hold-open';const identityABA=w.showApp(aid);await wait(()=>release,'held identity ABA open');const resumeIdentity=release;$('token').value='synthetic-test-B';$('connect').click();await wait(()=>w.eval('token')==='synthetic-test-B'&&$('project-select').value==='','other real identity logged in');$('token').value='synthetic-test-A';$('connect').click();await wait(()=>w.eval('token')==='synthetic-test-A'&&$('project-select').value===info.project,'original identity logged back in');resumeIdentity();await identityABA;check($('app-history').textContent===''&&$('app-manifest').textContent===''&&$('manifest-report-form').hidden,'real identity ABA cannot restore late app inspect');await w.showApp(aid);
 mode='hold-history';const pending=w.readManifestHistory();await wait(()=>release,'held history');const resume=release;w.clearApp();resume();await pending;check($('app-history').textContent===''&&$('manifest-report-form').hidden,'late selection history cannot restore cleared protected Report');
 mode='hold-open';const opening=w.showApp(aid);await wait(()=>release,'held open');const resumeOpen=release;$('project-select').value=info.other;w.clearApp();resumeOpen();await opening;check($('app-manifest').textContent===''&&$('manifest-report-form').hidden,'late cross-project app read cannot restore manifest');
 $('project-select').value=info.project;await w.showApp(aid);facts(500);mode='hold-preview';const abaSubmit=w.runManifestReport();await wait(()=>release,'held ABA preview');const resumeABA=release;check(!$('app-output').textContent.includes('已接受新 Run')&&$('manifest-report-trip').disabled&&$('manifest-report-retry').disabled,'new sending clears previous current receipt and freezes typed controls');w.clearApp();await w.showApp(aid);check($('manifest-report-submit').disabled&&$('manifest-report-retry').disabled,'same-app reopened during old sending cannot duplicate pending operation');resumeABA();await abaSubmit;check(!$('manifest-report-submit').disabled&&$('manifest-report-retry').hidden&&!$('app-output').textContent.includes('已接受新 Run'),'old accepted ABA response reconciles lock without restoring stale current receipt');
 // The accepted ABA Run is completed using the same ordinary Worker before a later enqueue.
 await work('allow');await w.readManifestHistory();
 $('project-select').value=info.project;await w.showApp(aid);facts(500);mode='hold-preview';const submitting=w.runManifestReport();await wait(()=>release,'held preview');const resumeSubmit=release;$('token').value='synthetic-test-B';$('connect').click();await wait(()=>$('manifest-report-form').hidden,'identity cleared');resumeSubmit();await submitting;check($('app-output').textContent===''&&$('app-history').textContent==='','late accepted submit cannot restore another identity');
 await assert.rejects(w.showApp(aid));const denied=await fetch(info.base+'/api/apps/'+aid,{headers:{Authorization:'Bearer synthetic-test-B'}});check(denied.status===403&&$('app-manifest').textContent===''&&$('app-history').textContent==='','actual unprivileged identity inspect is denied and cannot display protected app evidence');
 check(requests.filter(r=>r.method==='POST'&&r.path.includes('/apps/')).every(r=>!('report'in r.body)&&!('candidate'in r.body)&&!('gold'in r.body)&&!('replay'in r.body)&&!('runtime_id'in r.body)),'no caller Report/Candidate/Replay/gold/authority');
 const result={status:'PASS',checks,loaded_source_sha256:hashes,requests,requests_outside_origin:0,actual_mock_requests:7,live_requests:0,native:'NOT_RUN',semantic:'UNKNOWN',overall:'NOT_ACCEPTED'};fs.writeFileSync(path.join(root,'results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
}catch(e){fs.writeFileSync(path.join(root,'driver-failure.json'),JSON.stringify({status:'FAIL',checks,loaded_source_sha256:hashes,requests,error:e.message},null,2));console.error(e.stack);process.exitCode=1;}finally{dom?.window.close();}})();
