'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{JSDOM}=require('jsdom');
const root=process.argv[2],info=JSON.parse(fs.readFileSync(path.join(root,'info.json'))),checks=[],requests=[],hashes={};
let dom,w,$,mode='',release;
const check=(ok,label)=>{assert(ok,label);checks.push(label);};
const wait=async(fn,label)=>{const end=Date.now()+6000;while(Date.now()<end){if(fn())return;await new Promise(r=>setTimeout(r,10));}throw Error('Timeout '+label);};
async function setup(){
 dom?.window.close();const html=await(await fetch(info.base)).text();hashes['index.html']=crypto.createHash('sha256').update(html).digest('hex');dom=new JSDOM(html,{url:info.base,runScripts:'dangerously'});w=dom.window;$=id=>w.document.getElementById(id);
 w.fetch=async(url,opts={})=>{const target=new URL(url,info.base);assert.equal(target.origin,info.base);const entry={path:target.pathname,method:opts.method||'GET',body:opts.body&&JSON.parse(opts.body)};requests.push(entry);
 if(mode==='later-422'&&entry.method==='POST'&&entry.path.endsWith('/previews')){mode='';return {ok:false,status:422,json:async()=>({detail:[{msg:'controlled later 422 after unknown'}]})};}
 const response=await fetch(target,opts);
 if(mode==='lost-promote'&&entry.path.endsWith('/manifest-preview')){mode='';throw TypeError('Lost accepted promotion receipt');}
 if(mode==='bad-promote'&&entry.path.endsWith('/manifest-preview')){mode='';const bad=await response.json();delete bad.fingerprint;return {ok:true,json:async()=>bad};}
 if(mode==='lost-preview'&&entry.path.endsWith('/previews')&&entry.method==='POST'){mode='';throw TypeError('Lost accepted preview receipt');}
 if(mode==='bad-preview'&&entry.path.endsWith('/previews')&&entry.method==='POST'){mode='';const bad=await response.json();delete bad.phase;return {ok:true,json:async()=>bad};}
 if(mode==='hold-history'&&entry.path.endsWith('/history')){mode='';await new Promise(r=>release=r);release=null;}
 if(mode==='hold-open'&&entry.path.startsWith('/api/apps/')){mode='';await new Promise(r=>release=r);release=null;}
 if(mode==='hold-preview'&&entry.path.endsWith('/previews')&&entry.method==='POST'){mode='';await new Promise(r=>release=r);release=null;}
 return response;};
 for(const name of ['app.js','internal.js','protocol.js','use.js','conditional-runs.js','conditional-apps.js','report-manifest.js']){const code=await(await fetch(info.base+'/'+name)).text();hashes[name]=crypto.createHash('sha256').update(code).digest('hex');const s=w.document.createElement('script');s.textContent=code;w.document.body.append(s);}
 $('token').value='synthetic-test-A';$('connect').click();await wait(()=>$('project-select').value===info.project&&$('login').hidden,'identity/project');await w.refreshApps();
}
function facts(amount,receipt=true){for(const[k,v]of Object.entries({trip:'true',receipt:String(receipt),approved:'false',amount:String(amount),days:'2'}))$('manifest-report-'+k).value=v;}
const work=async phase=>{const r=await fetch(info.base+'/test-only-manifest-worker/'+phase,{method:'POST'});assert(r.ok,await r.text());};
(async()=>{try{
 await setup();await w.openReportApp(info.named);check(!$('report-manifest-promote').hidden,'named saved wrapper exposes explicit canonical promotion');mode='lost-promote';await w.promoteReportManifest();check(!$('report-manifest-promote-retry').hidden&&$('report-manifest-promote').disabled,'lost accepted promotion freezes intent');mode='bad-promote';await w.promoteReportManifest(true);check(!$('report-manifest-promote-retry').hidden,'malformed promotion preserves original intent');await w.promoteReportManifest(true);
 const promotions=requests.filter(r=>r.path.endsWith('/manifest-preview'));check(promotions.length===3&&promotions.every(r=>JSON.stringify(r.body)===JSON.stringify(promotions[0].body)),'promotion retries exact body/key');check(promotions.every(r=>Object.keys(r.body).sort().join(',')==='expected_app_fingerprint,request_key'),'promotion caller supplies no program or authority');
 const catalog=await(await fetch(info.base+'/api/apps',{headers:{Authorization:'Bearer synthetic-test-A'}})).json();const aid=catalog.items.find(a=>a.input_guidance.mode==='BOUNDED_REPORT').id;
 await setup();check($('app-list').textContent.includes('Saved hypothetical travel report')&&$('condition-run-plan').hidden,'fresh generic directory lists canonical persisted app without source context');await w.showApp(aid);
 check(!$('manifest-report-form').hidden&&$('app-preview-form').hidden&&$('internal-panel').hidden&&$('csv-extraction-panel').hidden,'generic AppManifest opens dedicated typed Scenario without old lifecycle');check($('manifest-report-amount').value===''&&$('manifest-report-trip').value==='','new page does not prefill source facts');check($('app-manifest').textContent.includes('bounded_report')&&$('app-manifest').textContent.includes('workflow'),'real canonical manifest displayed');
 facts(500);mode='lost-preview';await w.runManifestReport();check(!$('manifest-report-retry').hidden&&$('manifest-report-submit').disabled,'lost accepted preview locks inputs');mode='bad-preview';await w.runManifestReport(true);mode='later-422';await w.runManifestReport(true);check(!$('manifest-report-retry').hidden&&$('manifest-report-submit').disabled,'later 422 after unknown cannot release frozen intent');await w.runManifestReport(true);await work('allow');await w.readManifestHistory();
 facts(680,false);await w.runManifestReport();await work('block');await w.readManifestHistory();check($('app-history').textContent.includes('ALLOW')&&$('app-history').textContent.includes('BLOCK'),'two new Scenarios yield independent actual ALLOW/BLOCK Reports');
 const previews=requests.filter(r=>r.path.endsWith('/previews')&&r.method==='POST');check(previews.slice(0,4).every(r=>JSON.stringify(r.body)===JSON.stringify(previews[0].body)),'lost malformed later422 recovery preserves exact Scenario and key');check(previews.every(r=>Object.keys(r.body).sort().join(',')==='expected_candidate_fingerprint,input,request_key'),'cold caller supplies only typed input/version/key');
 await setup();await w.showApp(aid);check($('app-history').textContent.includes('ALLOW')&&$('app-history').textContent.includes('BLOCK'),'second fresh page reloads actual distinct Run history');const history=await(await fetch(info.base+`/api/projects/${info.project}/apps/${aid}/history`,{headers:{Authorization:'Bearer synthetic-test-A'}})).json();check(history.history.length===2&&new Set(history.history.map(x=>x.run.run_id)).size===2,'two durable history records bind different actual Run IDs');
 mode='hold-history';const pending=w.readManifestHistory();await wait(()=>release,'held history');const resume=release;w.clearApp();resume();await pending;check($('app-history').textContent===''&&$('manifest-report-form').hidden,'late selection history cannot restore cleared protected Report');
 mode='hold-open';const opening=w.showApp(aid);await wait(()=>release,'held open');const resumeOpen=release;$('project-select').value=info.other;w.clearApp();resumeOpen();await opening;check($('app-manifest').textContent===''&&$('manifest-report-form').hidden,'late cross-project app read cannot restore manifest');
 $('project-select').value=info.project;await w.showApp(aid);facts(500);mode='hold-preview';const submitting=w.runManifestReport();await wait(()=>release,'held preview');const resumeSubmit=release;$('token').value='synthetic-test-B';$('connect').click();await wait(()=>$('manifest-report-form').hidden,'identity cleared');resumeSubmit();await submitting;check($('app-output').textContent===''&&$('app-history').textContent==='','late accepted submit cannot restore another identity');
 check(requests.filter(r=>r.method==='POST'&&r.path.includes('/apps/')).every(r=>!('report'in r.body)&&!('candidate'in r.body)&&!('gold'in r.body)&&!('replay'in r.body)&&!('runtime_id'in r.body)),'no caller Report/Candidate/Replay/gold/authority');
 const result={status:'PASS',checks,loaded_source_sha256:hashes,requests,requests_outside_origin:0,actual_mock_requests:5,live_requests:0,native:'NOT_RUN',semantic:'UNKNOWN',overall:'NOT_ACCEPTED'};fs.writeFileSync(path.join(root,'results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
}catch(e){console.error(e.stack);process.exitCode=1;}finally{dom?.window.close();}})();
