'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{JSDOM}=require('jsdom');
const root=process.argv[2],info=JSON.parse(fs.readFileSync(path.join(root,'info.json'))),checks=[],requests=[],hashes={};
let dom,w,$,fault='',release,held,page;
const check=(value,label)=>{assert(value,label);checks.push(label);};
const wait=async(fn,label)=>{const end=Date.now()+6000;while(Date.now()<end){if(fn())return;await new Promise(r=>setTimeout(r,10));}throw Error('Timeout '+label);};
async function idle(){if(!page)return;await wait(()=>page.requests===0&&page.actions.size===0,'page HTTP/actions drained');await new Promise(r=>setImmediate(r));if(page.errors.length)throw page.errors[0];}
function trackHandlers(window,current){for(const name of ['onclick','onchange','onsubmit']){const d=Object.getOwnPropertyDescriptor(window.HTMLElement.prototype,name);Object.defineProperty(window.HTMLElement.prototype,name,{...d,set(fn){d.set.call(this,typeof fn==='function'?function(...args){const result=fn.apply(this,args);if(result&&typeof result.then==='function'){const action=Promise.resolve(result);current.actions.add(action);action.then(()=>current.actions.delete(action),e=>{current.errors.push(e);current.actions.delete(action);});}return result;}:fn);}});}window.addEventListener('error',e=>current.errors.push(e.error||Error(e.message)));}
async function setup(){
 await idle();dom?.window.close();dom=new JSDOM(await(await fetch(info.base)).text(),{url:info.base,runScripts:'dangerously'});w=dom.window;$=id=>w.document.getElementById(id);page={requests:0,actions:new Set(),errors:[]};trackHandlers(w,page);w.setInterval=()=>0;const current=page;
 // This fixture verifies explicit navigation and display only; polling NOT_RUN.
 w.fetch=async(url,opts={})=>{current.requests++;try{const target=new URL(url,info.base);assert.equal(target.origin,info.base);const entry={path:target.pathname,method:opts.method||'GET',body:opts.body&&JSON.parse(opts.body)};requests.push(entry);const begin=performance.now();const response=await fetch(target,opts);entry.status=response.status;entry.elapsed_ms=Math.round(performance.now()-begin);if((fault==='hold-derive'&&entry.path.endsWith('/derive'))||(fault==='hold-plan'&&entry.path.endsWith('/plans'))){const phase=fault;fault='';held=phase;await new Promise(r=>release=r);held=null;}if(fault==='lost-definition'&&entry.method==='POST'&&entry.path.endsWith('/report-presentations')){fault='';throw TypeError('Lost accepted definition');}if(fault==='lost-check'&&entry.method==='POST'&&entry.path.endsWith('/checks')){fault='';throw TypeError('Lost accepted check');}if(fault==='bad-check'&&entry.method==='POST'&&entry.path.endsWith('/checks')){fault='';const data=await response.json();data.result_binding.version++;return{ok:true,status:201,json:async()=>data};}return response;}finally{current.requests--;}};
 for(const name of ['app.js','internal.js','protocol.js','use.js','conditional-runs.js','conditional-apps.js','report-manifest.js']){const script=w.document.createElement('script');const code=await(await fetch(info.base+'/'+name)).text();hashes[name]=crypto.createHash('sha256').update(code).digest('hex');script.textContent=code;w.document.body.append(script);}
 $('token').value='synthetic-test-A';$('connect').click();await wait(()=>$('project-select').value===info.project&&$('login').hidden,'connect');await idle();await w.refreshApps();await w.showApp(info.app,info.project);await wait(()=>w.document.querySelector('.report-presentation-propose'),'presentation controls');
}
(async()=>{try{
 await setup();check(w.document.querySelector('.report-view-text').textContent==='ALLOW','original declared decision text rendered');
 const button=()=>w.document.querySelector('.report-presentation-propose'),confirm=()=>w.document.querySelector('.report-presentation-confirm');
 fault='hold-derive';button().click();await wait(()=>held==='hold-derive','held actual derive response');
 const postsAtDerive=requests.filter(r=>r.method==='POST').length;$('project-select').value=info.other;await $('project-select').onchange();check(!$('app-history').textContent.includes('ALLOW'),'project navigation clears old result');release();await wait(()=>held===null,'release late derive');await idle();check(requests.filter(r=>r.method==='POST').length===postsAtDerive,'late derive cannot continue plan or definition writes');check(!w.document.querySelector('.report-presentation-controls'),'late derive cannot repaint other project');
 $('project-select').value=info.project;await $('project-select').onchange();await w.showApp(info.app,info.project);
 fault='hold-derive';button().click();await wait(()=>held==='hold-derive','held same-app derive response');const abaPosts=requests.filter(r=>r.method==='POST').length;w.clearApp();await w.showApp(info.app,info.project);check(button().disabled,'same-app reopened while old sending cannot duplicate intent');release();await wait(()=>held===null,'release same-app old response');await idle();check(!button().disabled,'late same-app completion reconciles new controls');check(requests.filter(r=>r.method==='POST').length===abaPosts,'same-app old completion cannot continue automatic writes');
 fault='hold-plan';button().click();await wait(()=>held==='hold-plan','held actual plan response');const postsAtPlan=requests.filter(r=>r.method==='POST').length;w.clearApp();w.eval("token='synthetic-test-B'");release();await wait(()=>held===null,'release late plan');await idle();check(requests.filter(r=>r.method==='POST').length===postsAtPlan,'late plan after identity change cannot submit definition');check(!$('app-history').children.length,'late plan cannot repaint cleared app');w.eval("token='synthetic-test-A'");await w.showApp(info.app,info.project);
 fault='lost-definition';button().click();await wait(()=>!button().disabled&&button().textContent.includes('恢复'),'lost definition recovery');
 const original=requests.find(r=>r.method==='POST'&&r.path.endsWith('/report-presentations'));
 check(!!original,'definition submitted over actual HTTP');check(original.body.view.component_ref==='text'&&original.body.view.output_field==='explanation','only two closed View fields');check(Object.keys(original.body.view).length===2,'no expression or HTML definition');
 button().click();await wait(()=>!confirm().hidden&&!confirm().disabled,'recovered definition');
 const definitions=requests.filter(r=>r.method==='POST'&&r.path.endsWith('/report-presentations'));check(definitions.length===2&&JSON.stringify(definitions[0].body)===JSON.stringify(definitions[1].body),'lost definition uses exact original key and version');check(button().disabled,'accepted immutable draft cannot resubmit new definition');
 check(w.document.querySelectorAll('.report-view-text').length===1,'unchecked draft does not render new version');
 fault='bad-check';confirm().click();await wait(()=>!confirm().disabled&&confirm().textContent.includes('恢复'),'bad check reject');check(w.document.querySelectorAll('.report-view-text').length===1,'wrong result version cannot render explanation');
 fault='lost-check';confirm().click();await wait(()=>!confirm().disabled&&confirm().textContent.includes('恢复'),'lost check recovery');check(w.document.querySelectorAll('.report-view-text').length===1,'lost receipt does not imply checked presentation');
 confirm().click();await wait(()=>confirm().disabled&&w.document.querySelectorAll('.report-view-text').length===2,'exact check accepted');
 const submissions=requests.filter(r=>r.method==='POST'&&r.path.endsWith('/checks'));check(submissions.length===3&&submissions.every(r=>JSON.stringify(r.body)===JSON.stringify(submissions[0].body)),'all unknown check recoveries retain exact patch fingerprint and key');
 let texts=[...w.document.querySelectorAll('.report-view-text')];check(texts[0].textContent==='ALLOW','original computation display preserved');check(texts[1].textContent===info.explanation,'new explanation equals archived server output');check(!w.reportExecuted,'script-shaped explanation remains inert text');check(!texts[1].querySelector('script'),'no HTML element interpreted');
 check(texts[1].parentNode.textContent.includes('PROJECT BLOCKED_PARTIAL'),'project incomplete label retained');check(texts[1].parentNode.textContent.includes('PENDING')&&texts[1].parentNode.textContent.includes('NOT_ACCEPTED'),'material and acceptance pending labels');
 const changedPosts=requests.filter(r=>r.method==='POST');check(changedPosts.every(r=>r.path.includes('/delivery-graph/')),'no execution or model request from display flow');
 const beforeRestart=requests.length;await setup();texts=[...w.document.querySelectorAll('.report-view-text')];check(texts.length===2&&texts[1].textContent===info.explanation,'cold browser restores durable presentation receipt');check(!requests.slice(beforeRestart).some(r=>r.method==='POST'),'cold restore performs no writes');check(!w.reportExecuted,'cold text rendering remains inert');
 await w.showApp(info.app,info.project);check(w.document.querySelectorAll('.report-view-text').length===2,'fresh authorization/readback preserves old and new versions');
 check(Object.keys(hashes).length===7,'all seven actual product scripts fingerprinted');
 await idle();
 fs.writeFileSync(path.join(root,'results.json'),JSON.stringify({status:'PASS',checks,requests,hashes,native_browser:'NOT_RUN',material:'SYNTHETIC_RESULT_ONLY',overall:'NOT_ACCEPTED'},null,2));console.log(JSON.stringify({status:'PASS',checks:checks.length}));
 }catch(e){fs.writeFileSync(path.join(root,'failure.json'),JSON.stringify({error:e.stack,requests,hashes,html:$?.('app-history')?.textContent,errors:page?.errors?.map(e=>e.stack),pending_requests:page?.requests,pending_actions:page?.actions?.size},null,2));console.error(e.stack);process.exitCode=1;}finally{await idle();dom?.window.close();}})();
