"""Independent hand-authored cases: no answers generated by the checker or runtime gold."""

import copy
import json
from pathlib import Path

import httpx
import pytest
from sqlalchemy import select, update

from sim2act.conditional_checks import public_contract
from sim2act.db import fingerprint, grants, meta, resources
from sim2act.model import InternModel, parse_response

POLICY = Path("docs/evidence/model-protocol-preparation-20261006/materials/a-source/policy.txt")


def report(states, decision, actions):
    lines = POLICY.read_text().splitlines()
    return {
        "findings": [
            {
                "rule_id": rid,
                "applies": state,
                "citation": {"line": number, "quote": lines[number - 1]},
            }
            for rid, number, state in zip(["R1", "R2", "R3"], [3, 4, 5], states, strict=True)
        ],
        "decision": decision,
        "next_actions": actions,
        "deadline_days": 10,
        "absolute_date": "UNKNOWN",
        "receipt_restarts_deadline": False,
        "explanation": "Synthetic hand-authored proposal; prose is not independently graded.",
    }


def request(env, facts=(True, 680, True, False, 2), proposed=None):
    client, pid = env[2], env[5]
    reply = client.post(
        f"/api/projects/{pid}/resources",
        json={
            "name": "public-synthetic-policy.txt",
            "format": "txt",
            "content": POLICY.read_text(),
        },
    )
    assert reply.status_code == 201
    return {
        "resource_id": reply.json()["id"],
        "expected_source_hash": public_contract()["source_hash"],
        "expected_contract_fingerprint": public_contract()["fingerprint"],
        "scenario": dict(
            zip(
                ["trip_ended", "amount", "receipt_present", "approved", "elapsed_days"],
                facts,
                strict=True,
            ),
            kind="HYPOTHETICAL_EMPLOYEE",
        ),
        "report": proposed or report(["TRUE", "TRUE", "FALSE"], "BLOCK", ["obtain_prior_approval"]),
    }


def all_rows(store):
    with store.tx() as c:
        return {
            name: fingerprint([dict(r) for r in c.execute(select(table)).mappings()])
            for name, table in meta.tables.items()
        }


CASES = [
    ((True, 680, True, False, 2), ["TRUE", "TRUE", "FALSE"], "BLOCK", ["obtain_prior_approval"]),
    (
        (True, 500, True, None, 10),
        ["TRUE", "FALSE", "FALSE"],
        "ALLOW",
        ["submit_claim_and_receipt"],
    ),
    ((True, 501, True, True, 10), ["TRUE", "TRUE", "FALSE"], "ALLOW", ["submit_claim_and_receipt"]),
    ((True, 200, False, None, 5), ["TRUE", "FALSE", "TRUE"], "BLOCK", ["obtain_receipt"]),
    ((True, 680, False, True, 2), ["TRUE", "TRUE", "TRUE"], "BLOCK", ["obtain_receipt"]),
    ((True, 200, True, None, 11), ["TRUE", "FALSE", "FALSE"], "UNKNOWN", ["clarify_late_policy"]),
    ((None, None, None, None, None), ["UNKNOWN"] * 3, "UNKNOWN", ["clarify_facts"]),
    ((True, 501, True, None, 2), ["TRUE", "TRUE", "FALSE"], "UNKNOWN", ["clarify_facts"]),
    (
        (True, None, False, None, 2),
        ["TRUE", "UNKNOWN", "TRUE"],
        "BLOCK",
        ["obtain_receipt", "clarify_facts"],
    ),
    ((False, 200, True, None, None), ["FALSE", "FALSE", "FALSE"], "BLOCK", ["wait_trip_end"]),
    ((True, 200, True, None, None), ["TRUE", "FALSE", "FALSE"], "UNKNOWN", ["clarify_facts"]),
]


@pytest.mark.parametrize("facts,states,decision,actions", CASES)
def test_hand_authored_normal_unseen_and_unknown_inputs(env, facts, states, decision, actions):
    body = request(env, facts, report(states, decision, actions))
    before = all_rows(env[0])
    response = env[2].post(f"/api/projects/{env[5]}/conditional-checks", json=body)
    assert response.status_code == 200
    value = response.json()
    assert value["check_status"] == "PASS" and len(value["checks"]) == 13
    assert value["semantic_status"] == "UNKNOWN" and value["owner_acceptance"] == "PENDING"
    assert value["explanation_status"] == "NOT_CHECKED" and value["run_approval"] is False
    assert value["real_model_requests"] == 0 and value["formal_publication_enabled"] is False
    assert all_rows(env[0]) == before


def test_mock_proposal_is_not_gold_or_semantic_understanding(env):
    body = request(env)
    proposed = copy.deepcopy(body["report"])
    proposed["findings"].reverse()
    proposed["explanation"] = (
        "Different wording and report order are allowed. This is not measured comprehension."
    )
    wire = []

    def transport(req):
        wire.append(json.loads(req.content))
        return httpx.Response(
            200,
            json={
                "model": "Intern-S2",
                "usage": {"prompt_tokens": 10, "completion_tokens": 10, "total_tokens": 20},
                "choices": [
                    {
                        "finish_reason": "stop",
                        "message": {"role": "assistant", "content": json.dumps(proposed)},
                    }
                ],
            },
        )

    from dataclasses import replace

    model = InternModel(
        replace(env[1], live_enabled=True, token="SYNTHETIC_MOCK_ONLY"),
        httpx.MockTransport(transport),
    )
    raw = model.request([{"role": "user", "content": POLICY.read_text()}], [])
    message, calls = parse_response(raw)
    assert not calls and len(wire) == 1 and "expected_output" not in json.dumps(wire)
    body["report"] = json.loads(message["content"])
    response = env[2].post(f"/api/projects/{env[5]}/conditional-checks", json=body)
    assert response.json()["check_status"] == "PASS"
    assert response.json()["semantic_status"] == "UNKNOWN"


@pytest.mark.parametrize(
    "change,failed",
    [
        ("threshold", "R2.condition"),
        ("decision", "decision"),
        ("deadline", "deadline.original_calendar_days"),
        ("restart", "exception.no_deadline_restart"),
        ("absolute", "deadline.absolute_unknown"),
        ("case_line", "R2.source_citation"),
        ("quote", "R2.source_citation"),
        ("duplicate", "rules.complete_unique"),
        ("actions", "next_actions"),
    ],
)
def test_false_reports_have_specific_failed_checks(env, change, failed):
    body = request(env)
    r = body["report"]
    if change == "threshold":
        r["findings"][1]["applies"] = "FALSE"
    elif change == "decision":
        r["decision"] = "ALLOW"
    elif change == "deadline":
        r["deadline_days"] = 20
    elif change == "restart":
        r["receipt_restarts_deadline"] = True
    elif change == "absolute":
        r["absolute_date"] = "2099-01-01"
    elif change == "case_line":
        r["findings"][1]["citation"] = {"line": 6, "quote": POLICY.read_text().splitlines()[5]}
    elif change == "quote":
        r["findings"][1]["citation"]["quote"] = "Invented approval rule"
    elif change == "duplicate":
        r["findings"][2] = copy.deepcopy(r["findings"][0])
    elif change == "actions":
        r["next_actions"] = ["submit_claim_and_receipt"]
    response = env[2].post(f"/api/projects/{env[5]}/conditional-checks", json=body)
    assert response.status_code == 200 and response.json()["check_status"] == "FAIL"
    assert {"id": failed, "status": "FAIL"} in response.json()["checks"]
    assert response.json()["run_approval"] is False


def test_conflicting_facts_are_not_a_successful_input(env):
    body = request(
        env,
        (False, 200, True, None, 2),
        report(["FALSE", "FALSE", "FALSE"], "UNKNOWN", ["wait_trip_end", "clarify_facts"]),
    )
    value = env[2].post(f"/api/projects/{env[5]}/conditional-checks", json=body).json()
    assert (
        value["check_status"] == "FAIL"
        and {"id": "facts.consistent", "status": "FAIL"} in value["checks"]
    )


@pytest.mark.parametrize("field", ["amount", "elapsed_days"])
def test_bool_does_not_become_numeric_fact(env, field):
    body = request(env)
    body["scenario"][field] = True
    assert env[2].post(f"/api/projects/{env[5]}/conditional-checks", json=body).status_code == 422


def test_auth_source_version_and_contract_guards(env):
    store, _, client, _, other, pid, _ = env
    body = request(env)
    assert (
        client.post(
            f"/api/projects/{pid}/conditional-checks",
            json=body,
            headers={"Authorization": "Bearer synthetic-test-B"},
        ).status_code
        == 403
    )
    foreign = store.project(other, "Foreign check project")
    assert client.post(f"/api/projects/{foreign}/conditional-checks", json=body).status_code == 403
    changed = {**body, "expected_contract_fingerprint": "0" * 64}
    assert client.post(f"/api/projects/{pid}/conditional-checks", json=changed).status_code == 409
    changed = {**body, "expected_source_hash": "0" * 64}
    assert client.post(f"/api/projects/{pid}/conditional-checks", json=changed).status_code == 409
    with store.tx() as c:
        c.execute(
            update(grants).where(grants.c.resource_id == body["resource_id"]).values(revoked=True)
        )
    assert client.post(f"/api/projects/{pid}/conditional-checks", json=body).status_code == 403


def test_changed_source_bytes_cannot_match_registered_rule_contract(env):
    body = request(env)
    with env[0].tx() as c:
        c.execute(
            update(resources)
            .where(resources.c.id == body["resource_id"])
            .values(content="Changed rule")
        )
    response = env[2].post(f"/api/projects/{env[5]}/conditional-checks", json=body)
    assert response.status_code == 400
    assert response.json()["error"]["code"] == "VERIFICATION_FAILED"


def test_coherent_but_changed_source_hash_is_outside_registered_contract(env):
    import hashlib

    body = request(env)
    content = POLICY.read_text().replace("500", "900")
    digest = hashlib.sha256(content.encode()).hexdigest()
    with env[0].tx() as c:
        c.execute(
            update(resources)
            .where(resources.c.id == body["resource_id"])
            .values(content=content, hash=digest)
        )
    body["expected_source_hash"] = digest
    response = env[2].post(f"/api/projects/{env[5]}/conditional-checks", json=body)
    assert response.status_code == 409 and response.json()["error"]["code"] == "VERSION_CONFLICT"


def test_pinned_bytes_with_non_text_format_are_not_a_supported_rule_document(env):
    body = request(env)
    with env[0].tx() as c:
        c.execute(
            update(resources).where(resources.c.id == body["resource_id"]).values(format="csv")
        )
    response = env[2].post(f"/api/projects/{env[5]}/conditional-checks", json=body)
    assert (
        response.status_code == 400 and response.json()["error"]["code"] == "UNSUPPORTED_CAPABILITY"
    )
