import json,hashlib,subprocess,shutil
from pathlib import Path
root=Path('/tmp/native-session-failure-independent-review');repo=Path('/workspace/Sim2Act-native-session-diagnostic')
source='5acfd6cc8bc70abe79814dee1e3360737db708fe';head=subprocess.check_output(['git','rev-parse','HEAD'],cwd=repo,text=True).strip()
changed=subprocess.check_output(['git','diff','--name-only',source,head],cwd=repo,text=True).splitlines()
assert all(f.startswith('docs/') for f in changed)
m=json.loads((root/'source-manifest.json').read_text())
for file,expected in m['files'].items():
 if not file.startswith('docs/'):
  assert hashlib.sha256((repo/file).read_bytes()).hexdigest()==expected,file
for module in m['loaded_modules'].values():
 assert hashlib.sha256(Path(module['path']).read_bytes()).hexdigest()==module['sha256']
report={'decision':'PASS_BOUNDED_OFFLINE_DIAGNOSTIC_AND_FIXTURE_ROTATION','source_commit':source,'observed_final_head':head,'source_to_observed_difference':'DOCS_ONLY','base_commit':'e6c03cf15b7473ebce4cd3d5b8c4dcc06405a676','source_manifest':'source-manifest.json','independent_actual_http_combo':{'passed':2,'elapsed_seconds':34.29,'modes':['normal','PYTHONOPTIMIZE=1'],'fixture_scope':'Actual old26-equivalent durable state; protected browser26 not executed locally','old_jobs_each':5,'old_mock_attempts_each':4,'old_queued_each':0,'old_all_34_tables_fingerprints_retained':True,'single_api_same_port_transition':True,'fresh_normal_seed_not_clone':True,'separate_authority_baselines':True,'new_bound_checks_each':19,'manual_checks_each':22,'new_mock_attempts_each':4,'new_verified_resource_reads_each':2,'real_model_requests':0,'semantic_status':'UNKNOWN','overall_acceptance':'NOT_ACCEPTED'},'independent_oracles':{'short_pytest':'4PASS 2.19s','cases':['Slow old API stop: actual Node killed at short deadline; no replacement/READY','Correct fresh source ID but wrong SOURCE_HASH: no READY; all children collected','Real Node request publication: incomplete .tmp invisible until rename','READY publication: incomplete .tmp invisible until replace; exact fresh project/Bearer/SOURCE_HASH gate'],'safe_child_errors':'3PASS spawn ENOENT, malformed JSON, stderr DomainError; secret/path absent'},'initial_independent_failure':{'file':'independent-guards-first-expectation.log','classification':'TEST_ORACLE_TOO_NARROW','detail':'Wrong-hash readiness raises closed RuntimeError, not exclusively TimeoutExpired. Corrected exception oracle; no product change.'},'static_boundaries':{'product_src_diff_empty':True,'no_cancel_or_derived_scope_workarounds':True,'global_sealed_experiment_gate_unchanged':True,'old_protocol26_assertion_retained':True,'protected_context_audit_retained':True,'two_original_png_slots_retained':True,'node_timeout_seconds':150,'workflow_job_and_step_timeouts_unchanged':True,'safe_allowlist_error_classification':True,'atomic_ipc_both_directions':True,'owned_node_watchdog_finally_cancel_join':True},'limitations':['Original official Windows exception remains UNKNOWN because e6 discarded stderr; local sameDB global experiment binding failure is a causal reproduction, not proof of original Windows exception.','Protected Edge/Windows native, PNG emission, visual review, 900-second full job runtime NOT_RUN.','No full suite, PG, CI, push or real model requests; no whole Run/app publication acceptance.','Two normally seeded synthetic DBs have separate authority baselines; no cross-database unchanged-authority claim.','Watchdog preserves Node activity deadline; supervisor cleanup can extend elapsed time by bounded owned-child collection.'],'cleanup':{'owned_children_collected':True,'owned_fixture_databases_and_info_removed':True,'parent_resources_untouched':True},'evidence':{}}
shutil.rmtree(root/'combo-fixtures',ignore_errors=True)
for f in ['fake-bad-json','fake-stderr']:(root/f).unlink(missing_ok=True)
for name in ['source-manifest.json','combo-normal.json','combo-optimized.json','actual-combo.log','independent-guards-four.log','independent-guards-first-expectation.log','safe-errors.json','safe-errors.log','test_independent_rotation.py','test_independent_combo.py','safe-errors.cjs','architecture-review.json']:
 report['evidence'][name]={'sha256':hashlib.sha256((root/name).read_bytes()).hexdigest()}
(root/'final-review.json').write_text(json.dumps(report,ensure_ascii=False,indent=2))
print('final-review.json',hashlib.sha256((root/'final-review.json').read_bytes()).hexdigest())
print('source-manifest.json',hashlib.sha256((root/'source-manifest.json').read_bytes()).hexdigest())
