import pathlib,json,hashlib
R=pathlib.Path('/tmp/sim2act-native-remaining11-independent-5385-20261010');q=json.loads((R/'quick-results.json').read_text());c=json.loads((R/'close-results.json').read_text());passed=sum(r['pass'] for r in q+c);blocked=len(q+c)-passed;assert passed==11 and blocked==6
j={'verdict':'BLOCK','source_sha':'5385ac9293737cca8ed5dfeec990b760b240bf63','base_sha':'d49aab3e8023b3bf47a7f66577e557d2874c24ae','actual_Report_cases':17,'PASS':11,'BLOCK':6,'old_four_false_pass_now_refused':True,'valid_Recorder_metadata_trace_Report_exit':0,'false_pass_cases':['foreignstart','foreignfinish','wrongrequestevent','extranonrequestedsession','extranodephase','outoforder'],'source363_before_after_match':True,'unchanged_frozen_vs_d49':361,'products_same473':69,'only_summarize_AST_changes':True,'limits':{'all_phase_materials_synthetic':True,'no_11_test_execution':True,'Windows_native':False,'CI_PG':False,'real_models':0,'repo_source_tests_refs_write':False},'recommended_gate':'exact complete semantic event sequence plus required sets and single session; fail closed','global':'PROJECT PENDING/BLOCKED_PARTIAL; LIVE0; native/Edge/Node NOT_ACCEPTED; historical two timeouts OPEN'}
(R/'FINAL_REVIEW.json').write_text(json.dumps(j,indent=2));(R/'FINAL_REVIEW.md').write_text('''# Incremental independent remaining11 proof-gate review: BLOCK

Exact5385ac9293737cca8ed5dfeec990b760b240bf63; base archived d49aab3e8023b3bf47a7f66577e557d2874c24ae. Original d49BLOCK remains separate.

Actual Report CLI correctly rejects the four previous missingselection/missingfull/wronghash/wrongcount attacks. Skip, exit2 interruption, partial tail, wrong selection scope, foreignPID and duplicate required phase also reject. A synthetic complete trace emitted by the actual Recorder with real positive PID and all header/33phase/11finish metadata returns0 and complete=true.

Six incremental semantic variants still falsely return0/verified=true/complete=true: replace one node_start with a foreign node; replace one node_finish with a foreign node; rename requested first record from session_start to an unknown event; insert an extra unrequested session_start; insert an extra foreign-node passed phase; or swap a required node_start and its node_finish. The gate counts11 starts/finishes and compares finished cardinality but does not bind their sets to required11. It identifies requested headers by scope field rather than requiring the sole actual session_start, and ignores extra/unordered phases when computing per-node outcomes. These violate the explicitly requested exact start/finish/session and complete33phase boundaries.

Two self-authored finite matrices total17 actual Report CLI cases:11PASS/6BLOCK. These are synthetic diagnostic proof materials, not actual execution or acceptance of the target11 tests. Every material, summary and CLI log is retained; quick_probe uses Recorder emission to produce baseline metadata and mutates only private JSONL. The close_probe confirms old gates, additional semantic boundaries,363 hashes and byte bridges. No author test body or author result is independent evidence.

363Git/worktree/manifest paths match before/after. Only diagnostic summarize and its tests differ fromd49; the other361 frozen files are byte-identical and all69src remain same47388f573746daa27f8d5790ca358eef91378ad5. ASTs of other diagnostic functions/classes are identical, so prior default/PS/workflow/Node-lock and redaction limited results are bridged without rerunning their matrices.

Minimal next fix is complete semantic sequence closure: sole requested session_start first; full_collection→selection→selectedcollection; each fixed required node start→setup→call→teardown→finish in order; sole session_finish last, exact required start/finish/report sets,33unique reports and coherent PID. Nonsemantic collection summary may retain its normal place. Oldscope fallback remains diagnostic failure only. Root was notified it may edit only after5385 freeze seal; this review then accesses private sealed evidence only.

No Windows/CI/PG/actual model was run; no source/tests/refs edited. This is BLOCK for proof completeness, not a new product runtime failure or native execution result. Original remaining11/native/Edge/Node acceptance stays NOT_ACCEPTED; PROJECT PENDING/BLOCKED_PARTIAL, LIVE0 and both historical timeoutsOPEN. Copy explicit paths in COPY_WHITELIST; do not overwrite the originald49review or other sealed roots.
''')
files=[p for p in sorted(R.rglob('*')) if p.is_file() and p.name!='COPY_WHITELIST.json' and '__pycache__' not in p.parts];(R/'COPY_WHITELIST.json').write_text(json.dumps({'artifact_root':str(R),'source_sha':j['source_sha'],'verdict':'BLOCK','count':len(files),'files':[{'path':str(p.relative_to(R)),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size} for p in files]},indent=2));print(json.dumps({'verdict':'BLOCK','PASS':passed,'BLOCK':blocked,'whitelist':len(files)}))
