import pathlib,json,re,hashlib,base64,subprocess
ROOT=pathlib.Path(__file__).parent;SRC=pathlib.Path('/tmp/sim2act-csv-data-free-logic-20261010');REPO=pathlib.Path('/workspace/Sim2Act');SHA='4a4b6949fd159bd35c1ed1ed9d111426a27b706f'
raw=(SRC/'native-full.log').read_bytes();transport=json.loads((SRC/'native-full.log.transport.json').read_bytes());assert isinstance(transport,str) and transport.encode('utf-8')==raw
lines=raw.decode('utf-8').splitlines();events=[];chunks={};meta={};bc={};summary=None
for line in lines:
 t=re.sub(r'^\d{4}-\d\d-\d\dT\S+ ', '',line)
 if t.startswith('SIM2ACT_CI_DIAGNOSTIC '):events.append(json.loads(t.split(' ',1)[1]))
 elif t.startswith('SIM2ACT_CI_FULL_COLLECTION '):d=json.loads(t.split(' ',1)[1]);assert d['offset'] not in chunks;chunks[d['offset']]=d['nodes']
 elif t.startswith('Engineering diagnostics: '):assert summary is None;summary=json.loads(t[len('Engineering diagnostics: '):])
 elif t.startswith('SIM2ACT_BROWSER_FILE '):d=json.loads(t.split(' ',1)[1]);assert d['name'] not in meta;meta[d['name']]=d
for name,index,data in re.findall(r'SIM2ACT_BROWSER_CHUNK ([^\s]+) (\d+) ([A-Za-z0-9+/=]+)',raw.decode()):
 table=bc.setdefault(name,{});assert int(index) not in table;table[int(index)]=data
nodes=[n for off in sorted(chunks) for n in chunks[off]];assert sorted(chunks)==list(range(0,len(nodes),20)) and len(nodes)==len(set(nodes))==2337
expected=json.loads((REPO/'scripts/native-remaining11.json').read_text());assert len(expected)==11
assert summary['suite_complete'] and summary['selection_verified'] and summary['required_targets_complete'] and summary['collected']==summary['finished']==summary['started']==11 and summary['failure_reports']==0 and summary['exitstatuses']==[0]
assert summary['full_collection_count']==len(nodes) and summary['deselected_count']==2326
assert summary['full_collection_sha256']==hashlib.sha256(json.dumps(nodes).encode()).hexdigest()
reports=[e for e in events if e['event']=='node_report'];assert len(reports)==33 and all(r['outcome']=='passed' for r in reports);assert set(r['nodeid'] for r in reports)==set(expected)
starts=[e['nodeid'] for e in events if e['event']=='node_start'];finishes=[e['nodeid'] for e in events if e['event']=='node_finish'];assert starts==finishes and len(starts)==11 and set(starts)==set(expected)
for node in expected:assert [r['phase'] for r in reports if r['nodeid']==node]==['setup','call','teardown']
proofs=[];assert len(meta)==len(bc)==8
for name,m in meta.items():
 table=bc[name];assert sorted(table)==list(range(m['chunks']));data=base64.b64decode(''.join(table[i] for i in sorted(table)),validate=True);assert len(data)==m['bytes'] and hashlib.sha256(data).hexdigest()==m['sha256'];assert (SRC/'native-browser'/name).read_bytes()==data;proofs.append({**m,'raw_log_reassembly_and_saved_bytes_match':True})
assert 'protocol-results.json' not in meta
b=json.loads((SRC/'native-browser/browser-results.json').read_bytes());a=json.loads((SRC/'native-browser/agent-results.json').read_bytes());assert b['commit']==SHA and len(b['checks'])==67 and all(c['status']=='PASS' for c in b['checks'])
assert b['error']=={'name':'AssertionError','message':'protocol native has no unexpected script or console failures'} and b['status']=='FAIL';p=b['protocol'];assert p['status']=='PASS' and len(p['checks'])==26 and all(c['status']=='PASS' for c in p['checks']);assert a['status']=='PASS' and all(c['status']=='PASS' for c in a['checks']);assert p['boundRuns']['status']=='PASS' and p['conditional']['status']=='PASS'
u=p['unexpectedConsoleErrors'];assert len(u)==1 and u[0]['message']=='Failed to load resource: net::ERR_NO_BUFFER_SPACE' and u[0]['url'].endswith('/natural-goal.js')
j=json.loads((SRC/'native-jobs.json').read_text());assert isinstance(j,dict);job=j['jobs'][0];assert job['run_id']==38045426944 and job['id']==114193869021 and job['head_sha']==SHA and job['status']=='completed' and job['conclusion']=='failure';steps=[{'name':s['name'],'status':s['status'],'conclusion':s['conclusion'],'started_at':s['started_at'],'completed_at':s['completed_at']} for s in job['steps']];assert any(s['conclusion']=='failure' and 'Edge' in s['name'] for s in steps);assert next(s for s in steps if s['name']=='Stop owned API-worker and temporary PostgreSQL')['conclusion']=='success'
script=REPO/'scripts/browser-ci/internal-ui.cjs';scriptbytes=script.read_bytes();assert "check('protocol native has no unexpected script or console failures',result.protocol.unexpectedConsoleErrors.length===0);" in scriptbytes.decode();assert scriptbytes==subprocess.check_output(['git','show',SHA+':scripts/browser-ci/internal-ui.cjs'],cwd=REPO)
asset=REPO/'src/sim2act/web/natural-goal.js';assert asset.read_bytes()==subprocess.check_output(['git','show','fab14d542d7efe41d0b290e5b5baec433a1669a9:src/sim2act/web/natural-goal.js'],cwd=REPO)
sealed=pathlib.Path('/tmp/sim2act-csv-data-free-logic-independent-20261010/final-fixed');white=json.loads((sealed/'COPY_WHITELIST.json').read_text());assert white['count']==97
for f in white['files']:data=(sealed/f['path']).read_bytes();assert len(data)==f['bytes'] and hashlib.sha256(data).hexdigest()==f['sha256']
excerpts=[{'line':i+1,'text':t} for i,t in enumerate(lines) if any(s in t for s in ['11 passed, 2326 deselected','protocol native has no unexpected','subprocess.CalledProcessError','Run ./scripts/WindowsCI.ps1 -Phase Cleanup']) and len(t)<4000]
(ROOT/'LOG_EXCERPT.json').write_text(json.dumps(excerpts,indent=2));(ROOT/'ENGINEERING_DIAGNOSTICS.json').write_text(json.dumps(summary,indent=2));(ROOT/'BROWSER_FILE_VERIFICATION.json').write_text(json.dumps(proofs,indent=2));(ROOT/'JOB_STEPS.json').write_text(json.dumps(steps,indent=2));(ROOT/'VISIBLE_EVENTS.json').write_text(json.dumps(events,indent=2))
result={'source_sha':SHA,'run_id':job['run_id'],'job_id':job['id'],'native_job':'completed/failure','scope':'read-only terminal observation; zero new tests/CI','fixed11':{'passed':11,'failed':0,'skipped':0,'full_collection':2337,'explicit_deselected':2326,'phase_reports_passed':33,'JUnit_seconds':float(summary['junit'][0]['time']),'full_collection_hash':summary['full_collection_sha256'],'order_and_phases_verified':True},'Edge_wrapper':'FAIL','browser_main_checks':{'count':67,'status':'all PASS, does not override outer FAIL'},'agent_checks':{'count':len(a['checks']),'status':'PASS'},'protocol_legacy_checks':{'count':26,'status':'inner PASS only'},'protocol_bound_runs':{'status':p['boundRuns']['status'],'count':len(p['boundRuns']['checks'])},'protocol_conditional':{'status':p['conditional']['status'],'count':len(p['conditional']['checks'])},'unexpected_console_errors':u,'error':b['error'],'fixtureLifecycleError':b['fixtureLifecycleError'],'browser_saved_files':8,'expected_browser_files':9,'missing':'protocol-results.json (failed console check occurs before write)','cleanup':'success','raw_transport_decoded_UTF8_byte_exact':True,'raw_log_bytes':len(raw),'raw_log_sha256':hashlib.sha256(raw).hexdigest(),'source_asset_unchanged_from_fab':True,'sealed_final_fixed97_reverified_unchanged':True,'root_cause':'UNKNOWN; resource loader ERR_NO_BUFFER_SPACE is observed, not proof of a JS source defect or specific OS/browser/network cause','recommendation':'Keep this Edge wrapper failure OPEN, preserve original gate and budgets; no evidenced minimal source fix presently, no blind rerun or claim that passing inner checks erases it','whole_native/Windows/full2337':'NOT_ACCEPTED','new_logic_native_acceptance':'NOT_ACCEPTED: fixed11 does not select new feature nodes','real_models':0,'repo_writes':0,'STOP_ACK':True}
(ROOT/'NATIVE_OBSERVATION.json').write_text(json.dumps(result,indent=2));print(json.dumps({'run':job['run_id'],'fixed11':11,'Edge':'FAIL','browser_saved8':True,'unexpected_error':u,'rawsha':result['raw_log_sha256'],'sealed97_unchanged':True}))
