import pathlib,json,hashlib,subprocess,xml.etree.ElementTree as ET
R=pathlib.Path('/tmp/sim2act-native-prerequisites-independent-20261010');repo=pathlib.Path('/workspace/Sim2Act');sha='9002bf958f79972e576e831ebdf5e0d90fc44ea5';old='88cb3c64b5dcbaf3df7183ebbf72773547585e15'
f=json.loads(pathlib.Path('/tmp/sim2act-native-prerequisites-20261010/source-freeze.json').read_text());a={p:hashlib.sha256((repo/p).read_bytes()).hexdigest() for p in f['files']};g={p:hashlib.sha256(subprocess.check_output(['git','show',sha+':'+p],cwd=repo)).hexdigest() for p in f['files']};assert subprocess.check_output(['git','rev-parse','HEAD'],cwd=repo,text=True).strip()==sha and a==g==f['files']==json.loads((R/'source-before.json').read_text())['files'];assert len(a)==362
src={p:h for p,h in a.items() if p.startswith('src/')};assert len(src)==69
for p,h in src.items():assert hashlib.sha256(subprocess.check_output(['git','show','47388f573746daa27f8d5790ca358eef91378ad5:'+p],cwd=repo)).hexdigest()==h
changed=subprocess.check_output(['git','diff','--name-only',old,sha],cwd=repo,text=True).splitlines();assert set(changed)=={'scripts/WindowsCI.ps1','scripts/engineering-ci/package.json','scripts/engineering-ci/package-lock.json','tests/test_csv_dag.py'}
(R/'source-after.json').write_text(json.dumps({'sha':sha,'count':362,'git_worktree_manifest_match':True,'before_after_match':True,'files':a},indent=2));(R/'byte-bridge.json').write_text(json.dumps({'source_sha':sha,'base_sha':old,'changed':changed,'product_count':69,'all_product_equal_to_473':True,'freeze_362_before_after_match':True},indent=2))
suites=list(ET.parse(R/'ui-six.xml').getroot().iter('testsuite'));assert sum(int(s.attrib['tests']) for s in suites)==6 and all(s.attrib['failures']=='0' and s.attrib['errors']=='0' and s.attrib['skipped']=='0' for s in suites)
ui=[]
for p in sorted((R/'ui-six').glob('*/results.json')):
 d=json.loads(p.read_text());ui.append({'path':str(p.relative_to(R)),'status':d.get('status'),'checks':len(d.get('checks',[])),'source_sha':sha})
(R/'ui-summary.json').write_text(json.dumps({'nodes':6,'passed':6,'failed':0,'skipped':0,'seconds':43.50,'existing_oracles':True,'scenarios':ui,'total_driver_checks':sum(x['checks'] for x in ui)},indent=2))
ci=json.loads(pathlib.Path('/tmp/sim2act-native-diagnostics-20261010/ci-88-result.json').read_text());failed=ci['failures'];missing=[x['nodeid'] for x in failed if "Cannot find module 'jsdom'" in x['failure']];other=[x['nodeid'] for x in failed if x['nodeid'] not in missing];assert len(missing)==25 and other==['tests/test_csv_dag.py::test_three_actual_receipts_exact_report_and_old_request_recovery'];(R/'ci88-source-classification.json').write_text(json.dumps({'original_artifact':'/tmp/sim2act-native-diagnostics-20261010/ci-88-result.json','artifact_sha256':hashlib.sha256(pathlib.Path('/tmp/sim2act-native-diagnostics-20261010/ci-88-result.json').read_bytes()).hexdigest(),'source_sha':old,'failed_phase_reports':26,'missing_jsdom_nodes':missing,'other':other,'earlier_754_6eb_failed_node_equivalence':'NOT_ESTABLISHED','own_native_execution':False},indent=2))
probe=json.loads((R/'probe-results.json').read_text());assert probe['count']==42
review={'verdict':'LIMITED_PASS','source_sha':sha,'base_sha':old,'independent_harness_checks':42,'independent_missing_jsdom_negative':1,'existing_UI_nodes':6,'existing_UI_passed':6,'existing_UI_failed':0,'existing_UI_skipped':0,'UI_seconds':43.50,'existing_driver_checks':sum(x['checks'] for x in ui),'freeze':362,'source_products':69,'product_same_473':True,'limits':{'PS_Windows_runtime':False,'native_900_suite':False,'Edge_240':False,'Node_150_acceptance':False,'PG':False,'real_models':0,'whole_25_UI_revalidated':False,'historical_754_or_6eb_26_identity_equivalence':False},'preserved_harness_failure':'harness-first-run/probe.log (AST index error; corrected42 checks PASS)','historical_status':'Report GET idle6 OPEN; PG resources-history Future10 OPEN; PROJECT PENDING/BLOCKED_PARTIAL; LIVE0'}
(R/'FINAL_REVIEW.json').write_text(json.dumps(review,indent=2));(R/'FINAL_REVIEW.md').write_text(f'''# Independent prerequisite review: LIMITED_PASS

Exact source `{sha}`, base `{old}`. This review covers the engineering Node dependency prerequisite and uploaded CSV hash oracle correction. It does not accept native Windows, Edge, or the whole engineering suite.

The independently authored LF/CRLF probe passes 42 named checks. Raw LF and UTF8-upload hashes are `d5851306dd3ce833d82bced0abef12728f3e64e1ef1266ee8a9fef209a59619f`. Raw CRLF hashes to `a2b7f0dbc76768404782e4198149caeb404f9b0d20b1ba675c5bbfda1d954559`, while Path.read_text uploads the identical LF-normalized string. The archived old exact case passes LF and fails CRLF at its complete-output hash assertion. The new case passes both. Separate self-authored API oracles verify exact uploaded content/hash, independent Decimal total15, count2/quantity/text, three durable receipt operations, no model attempts/effects, original-key recovery, and foreign-owner403 with unchanged original result. Existing case assertions after the changed hash statement are AST-identical. Oracle/probe materials and the expected old failure are retained; they use private SQLite only.

Engineering package and lock bytes exactly match the existing `docs/evidence/engineering-pg-phase-20261008/first/node-tools` source. Effective lock versions are jsdom30.1.2 and playwright-core1.63.0. Static checks confirm JobRoot-owned prefix/cache, npm ci with lifecycle scripts disabled and explicit bounded fetch/no fallback, previous NODE_PATH restored in finally, and pre-pytest actual resolved package version and owned-path validation. Workflow/900 and240 budgets, Test.ps1, WindowsBrowserCI.ps1 and original browser lock are identical to88. PowerShell was not executed. On this Linux environment the supplied dependency directory actually resolves jsdom30.1.2; removing NODE_PATH reproduces MODULE_NOT_FOUND in the selected synthetic driver. No dependency was installed or changed by this review.

Six selected previously jsdom-missing existing UI node oracles passed with no skip/failure in43.50s: background poll and catalog routing synthetic drivers, column-patch real HTTP recovery/revocation, composition/all condition controls with worker/cold page, wiring1-1-1, and DAG internal reuse post/cold page. These are existing test oracles selected and executed by the reviewer, not self-authored independent UI assertions. Their recorded driver checks total {sum(x['checks'] for x in ui)}; source/hash/result artifacts are preserved in ui-six. This does not claim all25 failed UI nodes or their Windows behavior were revalidated. The original88 artifact independently classifies25 MODULE_NOT_FOUND phase reports and one CSV hash failure. Equivalence to unrecorded earlier754/6eb failed nodes is not established.

All362 frozen paths match Git, provided manifest and worktree before/after. All69 src product files are identical to47388f573746daa27f8d5790ca358eef91378ad5. Only WindowsCI.ps1, two new engineering lock files and test_csv_dag.py differ from88. Diagnostic observer tests were not rerun. First private probe reached a mistaken AST slice comparison; its log/script/databases are retained in harness-first-run. Correcting the slice and rerunning the finite private probe yields42 PASS; that harness error is not a product failure.

No native CI/PowerShell/PG/Edge/actual model was operated, nor were product/tests/refs edited. No claim of whole native acceptance or repair of every historical26 failure is made. Report GET idle6 and PG resources-history Future10 stay OPEN. Windows900/Edge240/Node150 NOT_ACCEPTED; PROJECT PENDING/BLOCKED_PARTIAL; LIVE0. Copy only the exact text/material files in COPY_WHITELIST.json; private SQLite binaries and cache files are omitted.
''')
files=[]
allowed={'.py','.json','.jsonl','.log','.md','.xml','.csv','.txt'}
for p in sorted(R.rglob('*')):
 if p.is_file() and p.suffix in allowed and '__pycache__' not in p.parts and '.pytest_cache' not in p.parts and p.name!='COPY_WHITELIST.json':files.append({'path':str(p.relative_to(R)),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
(R/'COPY_WHITELIST.json').write_text(json.dumps({'artifact_root':str(R),'source_sha':sha,'verdict':'LIMITED_PASS','count':len(files),'files':files},indent=2));print(json.dumps({'verdict':'LIMITED_PASS','source_sha':sha,'self_harness_checks':42,'missing_node_negative':1,'existing_ui':6,'driver_checks':sum(x['checks'] for x in ui),'whitelist_count':len(files)}))
